<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My profile</name>
   <tag></tag>
   <elementGuidId>3d0c3ac3-edb3-4382-91df-5c7ef1f201e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-659f40495f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-659f40495f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a3c7e1c-0e09-444d-ab82-653be6a69203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-659f40495f</value>
      <webElementGuid>9c386d88-51be-4068-8e74-4e9cfce5c962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>customizations__calltoaction</value>
      <webElementGuid>51e9995b-a866-4791-bb54-2a483fd93044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta </value>
      <webElementGuid>861452db-69b1-4ae1-9fde-762f01a6fdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/us/en/profile.html</value>
      <webElementGuid>2a86c26d-7149-4afd-9395-c1deb040a220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>e7b8d83f-a8f5-498d-b1de-d4ffec0901f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;_self&quot;}</value>
      <webElementGuid>c322cf5d-c525-4046-9ecc-06b59e4a8522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>befd15ff-d8b8-4323-98f5-a3f1cbc97ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          My profile
      </value>
      <webElementGuid>2fd19c00-9c9d-4bfa-993b-ce6195b6f79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-659f40495f&quot;)</value>
      <webElementGuid>28101931-2e17-4f3e-acc9-4b95d5c58bd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-659f40495f']</value>
      <webElementGuid>f1179b8d-ce37-4021-9f2d-1a9e65f0cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-659f40495f']/div/a</value>
      <webElementGuid>fdc72d8b-be07-4060-8b0c-960682d32fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello Testing Account2!'])[1]/following::a[1]</value>
      <webElementGuid>b74000cd-0545-4c65-aeda-ad04662162fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TA'])[1]/following::a[1]</value>
      <webElementGuid>a8c152c3-c72a-464e-89ca-b4692cf7347a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG OUT'])[1]/preceding::a[1]</value>
      <webElementGuid>1dfe9cd8-c8a1-407c-afc1-c41fd6914e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/us/en/profile.html')]</value>
      <webElementGuid>b18e8377-399d-40c1-b8a3-310317083faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>b68451a8-eee4-4daf-9bca-09e13d9b9e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-659f40495f' and @href = '/us/en/profile.html' and (text() = '
          
          My profile
      ' or . = '
          
          My profile
      ')]</value>
      <webElementGuid>4d422a81-506f-4a01-a04b-5842c52d7757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
