<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Interests, skills and knowledgeStartYou can quit anytime and Continue later</name>
   <tag></tag>
   <elementGuidId>6bb6d8a3-7c9e-4b8b-9643-e9cbe20ebd9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pf-root']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pf__welcomeScreen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>153337e5-411b-48cb-8614-1b6ac5728f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf__welcomeScreen</value>
      <webElementGuid>043b5e03-7a72-4b6b-a13c-8d6089dc081d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interests, skills and knowledgeStartYou can quit anytime and Continue later</value>
      <webElementGuid>8c083554-54f1-445e-8e54-698931ebaf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pf-root&quot;)/div[@class=&quot;pf__app&quot;]/div[@class=&quot;pf__wrapper&quot;]/div[@class=&quot;pf__formWrapper&quot;]/div[1]/div[@class=&quot;pf__welcomeScreen&quot;]</value>
      <webElementGuid>5b0acbe5-9dae-492d-a9ff-6b6239f6fa58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pf-root']/div/div/div/div/div</value>
      <webElementGuid>dd2588e4-aea1-40a3-935c-b49be0f37a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTES POUR LES RÉSIDENTS DES ÉTATS-UNIS'])[1]/following::div[26]</value>
      <webElementGuid>b6abd011-95ec-421a-af11-bce439682008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLITIQUE DE COOKIES'])[1]/following::div[27]</value>
      <webElementGuid>1b7a6733-8385-4d9b-93a6-0accbac67621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>bff9b92c-a2e1-470f-8661-29527119abee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later' or . = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later')]</value>
      <webElementGuid>9a6e8dbf-2c5a-4833-8e32-1ff8b238aedb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
