<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mot de passe_password</name>
   <tag></tag>
   <elementGuidId>2f601f16-d811-45a9-b768-b6adb5f3f043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-password-150360966288504350']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-password-150360966288504350</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>480cdb13-7839-444a-9090-dfc368a51582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1d013c5e-5830-4be6-8643-f25752e54235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>38919375-1462-44eb-b538-08705cadb081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>985ac4a0-0cdf-492e-a1ad-2acde7419e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-password</value>
      <webElementGuid>07a0e031-1acd-4485-9bbb-82685d05cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-valid-checkmark</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4aa7d66-2096-4e9d-9f54-26637b7c6f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c7b50fd-c599-4f2c-9136-0bcf3cb85490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-password-strength</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>4fd62936-a7a8-400e-8c31-5b6170ccb462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-conditional:show-password-strength</name>
      <type>Main</type>
      <value>viewport.width &lt; 920?up</value>
      <webElementGuid>c059d883-dd1b-4afa-88fe-9dfa5b3eda00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-password-150360966288504350</value>
      <webElementGuid>43acf1d9-7a22-4dc3-b399-8f86c41f8b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d8afeba-c7e7-41cb-b7a6-532d0e98d81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>437018d0-7be7-41c9-aab8-7767f99343a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-default-show-password-strength</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>eb1dc42c-cfab-470b-be9a-25bbe1d844c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3d5e0451-26d1-40bb-a9f1-8bca457a6def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-password-150360966288504350</value>
      <webElementGuid>ea559494-f90b-471a-8bf9-a3aa0c1e0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d82d3ac7-a530-407a-ab56-ea11986a86b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>73710a59-9f21-4c2b-8104-0645d66aea06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-password-150360966288504350&quot;)</value>
      <webElementGuid>a0d3607b-0694-40b2-85cc-95b167e7aacf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-password-150360966288504350']</value>
      <webElementGuid>b3a900cd-2d6d-4ceb-887d-9840833f355a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[5]/div/input</value>
      <webElementGuid>a897e199-e176-4f9c-8a1e-fea46464eb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[5]/div/input</value>
      <webElementGuid>08d9d42b-a90a-496c-a26b-e62f72f7e23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'gigya-password-150360966288504350']</value>
      <webElementGuid>2978f33c-7d41-4bec-82a6-cc4cf8fa8acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[6]/div/input</value>
      <webElementGuid>c16f461d-a885-44b6-a1c3-c1c60b25a61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[6]/div/input</value>
      <webElementGuid>080e667f-fb96-42af-a924-5663315b52f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
