<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prnom_profile.firstName</name>
   <tag></tag>
   <elementGuidId>6ffb1ec1-3609-4c79-b199-37cfc29f14e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-textbox-133868265315288100']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-textbox-133868265315288100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19fdd964-7f0f-4791-8a09-e5ba144e7f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb4603d0-ba41-48d7-9a12-6ecaec60d116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>2b43e0bf-7cd7-4af6-bc0a-8dbb96cc84a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-text</value>
      <webElementGuid>fafa56fe-194d-4405-9f62-fe9d127ab5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile.firstName</value>
      <webElementGuid>d33d05b8-970c-460c-86e8-3f5fa11575c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formnovalidate</name>
      <type>Main</type>
      <value>formnovalidate</value>
      <webElementGuid>fc16c2b4-62a7-4a46-9f3c-208ca1654cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62fe06d6-8283-42b3-bdfe-311c864b2dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1cc29c3-4397-4ebf-bf34-061423437da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-display-name</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_74745039052211940_DISPLAY_NAME']</value>
      <webElementGuid>756acf4e-ba37-424e-b711-860fd7eaccfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-textbox-133868265315288100</value>
      <webElementGuid>101e269b-648b-478b-8589-dee70e16ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3dba871b-8770-4341-ab21-7c2c7377dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>69f574d3-6052-4f15-849a-8246b72e4e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>profile.firstName</value>
      <webElementGuid>da83bf40-d6aa-4d10-84e6-203f88a22d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-textbox-133868265315288100</value>
      <webElementGuid>e8fa24d3-a088-4622-bb91-f184ee6f0f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edcd0fe6-7a9b-4a77-b0d9-230c942b2fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>Prénom</value>
      <webElementGuid>2bebc79f-cc54-4542-9993-a66dde645225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-textbox-133868265315288100&quot;)</value>
      <webElementGuid>c63a37f3-6c8e-4a30-b60c-9c91b4818e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-textbox-133868265315288100']</value>
      <webElementGuid>c7a69337-4332-4ac1-945f-ff32237a9783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[10]/div/div/input</value>
      <webElementGuid>775fd386-7b3b-486c-8cf4-ed540e9b1b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[10]/div/div/input</value>
      <webElementGuid>9f8ce892-f4ab-45c0-8a90-cd9999e69882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'profile.firstName' and @id = 'gigya-textbox-133868265315288100']</value>
      <webElementGuid>9c6e1470-fb9a-44b2-979c-7b642bb63d3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
