<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prfrences de communication_subscripti_11c1ef</name>
   <tag></tag>
   <elementGuidId>9e8c3a48-791a-41de-86dc-cf64942718e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-43250903962922090']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-43250903962922090</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abc765f5-f417-44b5-9d21-493d74cabfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>645c18e3-32dd-4d3a-bb2e-817c055eb132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>3014ee18-fe42-4c11-9d8a-691f344865c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscriptions.SKP.email.isSubscribed</value>
      <webElementGuid>05adc78e-8ead-44a9-a3f7-7c2a1443348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-43250903962922090</value>
      <webElementGuid>0c8bbd57-f5f3-4bcc-83b9-4514cd7b8d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16984cb1-9daa-4490-925b-67b2556268ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>736eee3b-f59d-4204-91d6-9bb3168a16fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>subscriptions.SKP.email.isSubscribed</value>
      <webElementGuid>33172327-5354-417f-842c-27a18c07b24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a86ba0cb-72e1-4e57-933b-2ac97c72b1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-43250903962922090</value>
      <webElementGuid>79bea7ef-6e49-47e7-8b8b-0882cb27d5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d0a62db-4c79-4604-b95c-99624d41f92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-43250903962922090&quot;)</value>
      <webElementGuid>c8362e77-05cf-4812-8be6-820975292d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-43250903962922090']</value>
      <webElementGuid>ef3ea3a1-2e4f-4f34-8da6-a10e393c901c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[24]/div/input</value>
      <webElementGuid>2b4ed15d-f231-499d-9132-fc93561192ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[24]/div/input</value>
      <webElementGuid>d4e35c17-fd59-4ad4-bc1a-86ab73212d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'subscriptions.SKP.email.isSubscribed' and @id = 'gigya-checkbox-43250903962922090']</value>
      <webElementGuid>145a9ced-ca6b-4ec2-9bb3-58637e42c946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
