<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pays_preferences.terms.HenkelSKPeAcad_dba1a9</name>
   <tag></tag>
   <elementGuidId>a6ff9770-1b9e-4f26-a97f-4301d094c7f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-151487198184346560']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-151487198184346560</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2102d926-70a4-42e6-b875-c2650df64317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>06e0038e-b829-4f4d-b2b9-86309d9d6abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>a24364d3-3f75-4f93-93c1-7ca1dc7dff7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelSKPeAcademyToS.isConsentGranted</value>
      <webElementGuid>e04a8137-cfe8-4326-98ad-fa573e09676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-151487198184346560</value>
      <webElementGuid>5d629efe-4478-444e-bec1-dc08d094def6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54a12b2e-66da-4eda-84c8-841238909d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>ebe3466f-5839-4491-a8d5-4727b3c0f78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelSKPeAcademyToS.isConsentGranted</value>
      <webElementGuid>68753e62-cd0b-4ec8-abd1-4fd35d73a332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c054c71e-9112-4c1d-88b9-870f78936dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-151487198184346560</value>
      <webElementGuid>161fca11-5f82-44f5-915c-039da7ce6b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8046853-5c8c-495b-bd14-442151fcc949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-151487198184346560&quot;)</value>
      <webElementGuid>cfa1d62e-9a37-46d9-b86b-ef87a3fc05a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-151487198184346560']</value>
      <webElementGuid>574d0b74-530a-4609-bbb0-788a5f82a366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[23]/div/input</value>
      <webElementGuid>25a18ea3-6b6c-4120-a945-1706739a2fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[23]/div/input</value>
      <webElementGuid>b8aa081d-2fd2-43de-b6e1-8828307016ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'preferences.terms.HenkelSKPeAcademyToS.isConsentGranted' and @id = 'gigya-checkbox-151487198184346560']</value>
      <webElementGuid>62d6cce2-5630-4af8-bbe3-eafaba1a830c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
