<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prfrences de communication_subscripti_c9f577</name>
   <tag></tag>
   <elementGuidId>2efed54d-a0fa-4d50-830f-8344ff257774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-1791737162387700']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-1791737162387700</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a24e5808-157a-43cb-b768-005d64bc54d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b8af88c-318c-4722-a50e-1a75bfe4c4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>33d3ca81-ff92-4777-8c2e-19bcf713e06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscriptions.SKP.personalization.email.isSubscribed</value>
      <webElementGuid>ba77fd4e-fef3-48aa-948e-ae2fdfb24d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-1791737162387700</value>
      <webElementGuid>eb482ed9-1be0-47da-a892-aa1ac4a2d2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01519d17-3f36-4fac-8e66-417b736b09a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>e7244d57-82f8-42ff-bdea-3f81cdb19681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>subscriptions.SKP.personalization.email.isSubscribed</value>
      <webElementGuid>1db3e4f2-ab95-4508-b23d-f3f03c2dd8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18454931-eb20-4a65-b503-87f72ab1ab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-1791737162387700</value>
      <webElementGuid>6a19526e-a5fb-495c-86ab-aaf40c81bdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77c6374a-9f16-4c59-9c0f-e1e8ea071312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-1791737162387700&quot;)</value>
      <webElementGuid>c01bb0e9-e764-4073-afe7-63488c84515e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-1791737162387700']</value>
      <webElementGuid>113d499b-68d6-43ac-9045-435e66566aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[25]/div/input</value>
      <webElementGuid>38c04a5e-a4c0-415c-8c04-e6c85096f285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[25]/div/input</value>
      <webElementGuid>b8afe363-bdb8-4a39-995b-dc5bf17bf39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'subscriptions.SKP.personalization.email.isSubscribed' and @id = 'gigya-checkbox-1791737162387700']</value>
      <webElementGuid>51d3f0df-bae5-4fff-b5ea-f3f4fc7cbe36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
