<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__data.SKP.ID</name>
   <tag></tag>
   <elementGuidId>17e8d399-4566-4d1d-beff-0d67a8b489e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-textbox-74320110375414270']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-textbox-74320110375414270</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68a2f407-f4d6-4e1d-b343-7311f6361e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>736ce4ea-80f1-48ba-a6f4-6c0ef38fc462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-text</value>
      <webElementGuid>9b3cd1b8-118f-4d04-832a-dc972ea318e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>05b4923c-538f-4bec-83e1-8fbfc2c917ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-valid-checkmark</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c611d59-7c37-4add-aeed-5a42df831632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab7ae504-12f6-4ad0-a4ad-b2892d1ec3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.SKP.ID</value>
      <webElementGuid>ed57f7db-8cfe-4110-921d-c62284cd8958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91d9db45-3ae0-46f1-8c3b-de1c6ba7803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-display-name</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_124174370706734750_DISPLAY_NAME']</value>
      <webElementGuid>2eaad2e4-b64a-478f-b26b-0c8b1784dd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-textbox-74320110375414270</value>
      <webElementGuid>ba1b0d58-2ece-49c7-8353-d309b2d35eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3e8a1a5-b2c2-4b05-b158-0c9949235ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>9a3f54ae-fa80-4054-a1ad-00ac455c82a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>data.SKP.ID</value>
      <webElementGuid>149fd934-1a3e-40b5-a888-61629ef7694f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-textbox-74320110375414270</value>
      <webElementGuid>7b7cbc68-f4dd-47d0-b6fd-5f05455af131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cdbeb621-ffb7-4b82-a79b-4917620ca499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>Numéro de client Schwarzkopf Professional</value>
      <webElementGuid>aa1a5cc3-3c32-49d5-a56b-b15278fce88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb827099-2c21-4403-9de7-16303a73faaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-textbox-74320110375414270&quot;)</value>
      <webElementGuid>5594e8d7-5993-4ba5-8164-4ca577c9b9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-textbox-74320110375414270']</value>
      <webElementGuid>85339ce8-87da-49e0-9043-46405f673855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[15]/div/input</value>
      <webElementGuid>ffec85bb-a591-42b5-a4be-986bc316ed85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[15]/div/input</value>
      <webElementGuid>80aeed99-fb69-476b-a375-4080d8c86d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'data.SKP.ID' and @id = 'gigya-textbox-74320110375414270']</value>
      <webElementGuid>f9e39209-e6a3-442a-b245-9bc6df14670b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
