<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prfrences de communication_subscripti_0ddd69</name>
   <tag></tag>
   <elementGuidId>2ef8fdf4-1a65-464c-bfb4-3dbb1a84bf07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-118137378675131230']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-118137378675131230</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69e06733-c0bb-4c88-bbef-08b1dbc850bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>337e147c-3cfd-4ec4-8e80-be056062a53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>684b8e67-82c5-4d13-8f28-0f9654f59e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscriptions.SKP.social.email.isSubscribed</value>
      <webElementGuid>b9c6731e-4fa2-49dc-9dbc-5487c1597e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-118137378675131230</value>
      <webElementGuid>3889d89c-20cb-46ad-af01-12fec225ae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ced3964-3a3e-476b-a11c-b9ca50cf0ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>b7a51404-0f16-4a22-ba1a-d4e0a22e3307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>subscriptions.SKP.social.email.isSubscribed</value>
      <webElementGuid>fe25bcc7-9ce3-4fd8-ac6d-c3b975228db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0bd1a81a-bb20-42b6-b453-c9ae37c9c560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-118137378675131230</value>
      <webElementGuid>a9b4ffeb-5571-4422-990f-b7513eddafc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf47e3dc-fe1a-483c-a4e6-b589a3ba5971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-118137378675131230&quot;)</value>
      <webElementGuid>e4f1d44d-47cb-4adc-ab72-3435cb49693f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-118137378675131230']</value>
      <webElementGuid>a2cf2546-63bb-446c-933b-c832c1525068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[26]/div/input</value>
      <webElementGuid>497a8551-eb2b-4845-b01c-d765278649e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[26]/div/input</value>
      <webElementGuid>1ffdbe5c-3519-4f16-9b14-7afc5938b020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'subscriptions.SKP.social.email.isSubscribed' and @id = 'gigya-checkbox-118137378675131230']</value>
      <webElementGuid>70060f7b-0f9f-4f1f-940a-5e2ca0c6ef6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
