<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>5d761a29-c299-4325-92e5-7a06116ef585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='RETOUR À L’ACCUEIL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7bb636b-058b-4bee-92ac-a6239710bd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1efbae59-03ee-4644-932c-08009488faf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a634fd4-1aea-43ab-8d68-f2b80f8b7421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>RETOUR À L’ACCUEIL</value>
      <webElementGuid>fe505e9c-798c-4037-a672-8f2d67412d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_608_1675777010179</value>
      <webElementGuid>d17c261e-8911-4db9-b082-76dde128bae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aadb6437-a3af-4f23-a924-d7f56c71734c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>template,instance</value>
      <webElementGuid>cfe77a93-ecbe-4470-967e-27f4f43ea583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-verification-sent-screen&quot;)/div[@class=&quot;gigya-layout-row&quot;]/a[@class=&quot;gigya-composite-control gigya-composite-control-link gigya-button-link&quot;]/input[1]</value>
      <webElementGuid>4002c435-6b1f-4de8-af8a-04bc0b8c9ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='RETOUR À L’ACCUEIL']</value>
      <webElementGuid>864deca3-bf5b-444f-af14-634e6635f567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gigya-verification-sent-screen']/div[4]/a/input</value>
      <webElementGuid>bacbcc84-624e-40a0-9713-d56e0d1d798d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>3c4fabc2-1aaa-499d-ba81-bf9f58f75cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>1f928743-0eee-48ea-a220-307eb8e5003d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='OUI']</value>
      <webElementGuid>b5200009-ba3b-4557-8d84-e8995cc2bdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[2]/div/a/input</value>
      <webElementGuid>86a8f6bd-f41f-413e-8c67-727d0d64c5f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
