<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mot de passe_password</name>
   <tag></tag>
   <elementGuidId>2f601f16-d811-45a9-b768-b6adb5f3f043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-password-150360966288504350</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-password-150360966288504350']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98e7be11-cd82-40d6-94a2-447c45b6f8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b810f783-69ea-4a48-9479-92960ae89737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d85f0b05-4bfa-4b5c-b57a-34a82f9d38c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ba56a6ec-3295-4a0a-a807-0489d823bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-password</value>
      <webElementGuid>b3223ea3-fa5c-4e7a-97f8-184efd3b1b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-valid-checkmark</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6f2fb61-a601-43b9-a6a3-7601d6cdc8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82fbac89-df21-43b7-9a17-02c5228be3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-password-strength</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>646bbb77-e0b2-4b05-8026-05e23107f0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-conditional:show-password-strength</name>
      <type>Main</type>
      <value>viewport.width &lt; 920?up</value>
      <webElementGuid>037031c7-acab-4baa-8c45-e0690c5d421a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-password-150360966288504350</value>
      <webElementGuid>ee08892f-1571-4d33-bcf7-c6ec231deab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e8d690c-78c8-4384-bf0a-1ee8bb56e267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>ba42a023-fd05-4044-b299-3c5cbc7339be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-default-show-password-strength</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>ad7cf261-8125-4c40-8835-23c98dcc2220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dcb7d537-8ada-4d3d-90a1-35e95fcdae30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-password-150360966288504350</value>
      <webElementGuid>e626961e-5a89-4d08-bf4f-8cfc490954de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21c60df0-3151-4cb9-91b4-303f682b16e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>235636da-0274-4aeb-8e77-4b407f666122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-password-150360966288504350&quot;)</value>
      <webElementGuid>f8fcca09-d33b-4065-bdd6-03f3b2933937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-password-150360966288504350']</value>
      <webElementGuid>f401b7a0-5c3a-4576-90d9-a716f2953bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[6]/div/input</value>
      <webElementGuid>de3edcaa-060a-4875-86c1-9a54df7f0c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[6]/div/input</value>
      <webElementGuid>72aa55a4-8d49-4934-8d79-2388fd47f8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'gigya-password-150360966288504350']</value>
      <webElementGuid>bafa14c5-3ea9-4781-99f8-3bf93211c508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
