<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Propritaire de salonChane de salonsS_4b2a29</name>
   <tag></tag>
   <elementGuidId>4168c57c-693d-4080-8134-fbb0cceffcaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gigya-dropdown-73235996620585280']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-dropdown-73235996620585280</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98dea8fe-2afd-4c0f-8335-d29642d7ec27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92279104-c013-4cdb-bc14-7e6bc814002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.SKP.role</value>
      <webElementGuid>d369fb3f-b1de-4661-ac9c-83d6ca65609b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a3a61aa-7e11-450d-9ff7-4c89fb312965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-dropdown-73235996620585280</value>
      <webElementGuid>3e0c1983-d691-4740-8f65-8586e0513b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56016aad-54fb-4b8b-825a-db30491fbf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>1240f364-ddf1-40eb-ad8a-452726de1ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>data.SKP.role</value>
      <webElementGuid>d17802f8-d70e-438e-bf5a-cc926bed0313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-dropdown-73235996620585280</value>
      <webElementGuid>ee4b07aa-05c0-4a82-bbfb-6cecaa329a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb30531c-b1e1-4705-b1dd-91ba5e8a9c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Propriétaire de salonChaîne de salonsStyliste professionnelStyliste mobileGrossisteDistributeur</value>
      <webElementGuid>8a5eb366-ec86-4860-9fdd-84a29d94489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-dropdown-73235996620585280&quot;)</value>
      <webElementGuid>f15581d1-639f-495a-bf58-9aa6bc92a2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gigya-dropdown-73235996620585280']</value>
      <webElementGuid>425a06df-9f9e-4b72-b168-87cd77355b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[13]/div/select</value>
      <webElementGuid>b21d2e4b-6570-4c41-821a-c1384f0d9e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Votre profession/type d', &quot;'&quot;, 'activité')])[1]/following::select[1]</value>
      <webElementGuid>e2bba386-ccba-4aff-be37-c7a5d0858146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations professionnelles'])[1]/following::select[1]</value>
      <webElementGuid>6e1cc787-6057-437b-9326-5a5cc0f3bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom du salon ou dénomination commerciale'])[1]/preceding::select[1]</value>
      <webElementGuid>02fdd59d-5fb5-46e3-9209-5c240342823f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[13]/div/select</value>
      <webElementGuid>3c5ee067-2b2a-4ebf-af65-baa3240c57af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'data.SKP.role' and @id = 'gigya-dropdown-73235996620585280' and (text() = 'Propriétaire de salonChaîne de salonsStyliste professionnelStyliste mobileGrossisteDistributeur' or . = 'Propriétaire de salonChaîne de salonsStyliste professionnelStyliste mobileGrossisteDistributeur')]</value>
      <webElementGuid>4cb09d12-eccf-4a20-b3cd-50a4000018c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
