<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mme.M.Div</name>
   <tag></tag>
   <elementGuidId>132a3640-243f-4afb-9e0a-68255682ea5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gigya-dropdown-149290914991369570']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-dropdown-149290914991369570</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>463b50b3-d05a-4859-80bc-2850b96eb67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>009a0573-8b63-48ee-bfb6-95a989e896e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.title</value>
      <webElementGuid>872f1bb7-ab38-4f52-9972-c17740ccc9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-dropdown-149290914991369570</value>
      <webElementGuid>0f44879e-cb77-4793-b766-dd70240495dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3835f793-5bde-4293-b235-e6c14ddaa8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>c4a68a14-6037-46e5-912a-2c79dcbc3759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>data.title</value>
      <webElementGuid>4131054e-a02a-4be6-be7b-a3f74a8d8b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-dropdown-149290914991369570</value>
      <webElementGuid>c2721dcc-f4a8-483d-bb89-dea440056e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61db5b56-2d55-4140-8285-cd522f19809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mme.M.Div.</value>
      <webElementGuid>443e61fc-1971-49cb-aee2-2c56aea2aa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-dropdown-149290914991369570&quot;)</value>
      <webElementGuid>9982cf4f-582e-4b04-a233-85987fa4d233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gigya-dropdown-149290914991369570']</value>
      <webElementGuid>1d28dc6a-476b-4469-9915-b23068aaa568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-register-form']/div[9]/div/select</value>
      <webElementGuid>6b84154d-d540-4b4e-93e5-c09f0d49ead4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titre'])[1]/following::select[1]</value>
      <webElementGuid>0d3112e6-91fe-4319-86bc-f703713b12e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations personnelles'])[1]/following::select[1]</value>
      <webElementGuid>b7853ef7-40a7-4571-9ac4-bb814abf21d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prénom'])[1]/preceding::select[1]</value>
      <webElementGuid>beb8d34d-199c-4f2d-94e0-16dc4b442eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nom'])[1]/preceding::select[1]</value>
      <webElementGuid>4281db50-ddbe-4479-9935-fa7535895b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[9]/div/select</value>
      <webElementGuid>1aa15924-6a3f-4758-9278-1f93760eb7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'data.title' and @id = 'gigya-dropdown-149290914991369570' and (text() = 'Mme.M.Div.' or . = 'Mme.M.Div.')]</value>
      <webElementGuid>c6420093-c060-4d9e-a3c9-5cc88fa47637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
