<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CATALOGUE_section-f3bc5ee279</name>
   <tag></tag>
   <elementGuidId>4d97139b-1ad8-41f1-aa44-b2c2f053f287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section-f3bc5ee279</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-f3bc5ee279']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f74b0c82-0668-4a18-8030-d6adc31595b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section-f3bc5ee279</value>
      <webElementGuid>c8e88c39-2ddd-40f0-a1aa-8051e79987c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section__content content limited-container customizations__section</value>
      <webElementGuid>4a46667f-e590-4f76-9d63-cdafcaaf4232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-f3bc5ee279&quot;)</value>
      <webElementGuid>a2a3b9b4-c06a-486c-ac64-5efdcbdd52ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section-f3bc5ee279']</value>
      <webElementGuid>7096182f-6cca-436e-9e65-c82040e39436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-2ae423d098']/heliux-section/div[3]</value>
      <webElementGuid>9935e022-0e02-4443-8061-968432295492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[2]/following::div[11]</value>
      <webElementGuid>d555414c-0475-4afc-a368-acc631d8a83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MON APPRENTISSAGE'])[2]/following::div[14]</value>
      <webElementGuid>cc305fdc-02af-4be9-ac0a-fc6d3c224342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUIVEZ-NOUS'])[1]/preceding::div[22]</value>
      <webElementGuid>eb8d5449-3387-4594-9219-62cbdb01250d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENTIONS LÉGALES'])[1]/preceding::div[41]</value>
      <webElementGuid>c23b30d9-9b6d-4195-a4d6-8ec44093a0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/heliux-section/div[3]/heliux-section/div[3]</value>
      <webElementGuid>1ee71578-3651-4538-9c27-21b5aa983d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section-f3bc5ee279']</value>
      <webElementGuid>49399034-fb58-4925-ac99-5df4883b8bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
