<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SENREGISTRER</name>
   <tag></tag>
   <elementGuidId>80b32261-1793-4d06-b9ce-6012a183c114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-78b26aa002']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-78b26aa002</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ec136bd-fd21-418a-91fa-dc0ac51436df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-78b26aa002</value>
      <webElementGuid>faa12291-7370-427c-8c06-4660e756e9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>customizations__calltoaction</value>
      <webElementGuid>1c4ddc24-c16d-4456-8755-39ea0ede560a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta </value>
      <webElementGuid>1dd4a17a-0844-47e8-b237-fda413ccf3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr/fr/bienvenue/enregistrer.html</value>
      <webElementGuid>7b2c993a-2948-4b98-82e7-71f62cc21803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;&quot;}</value>
      <webElementGuid>b0b60c7f-8dc3-4609-9df7-6524f49bf277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>aaed906b-abe7-413e-b04e-1c26b8621388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          S'ENREGISTRER
      </value>
      <webElementGuid>456e19be-e23f-4121-a845-efdcadb82222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-78b26aa002&quot;)</value>
      <webElementGuid>93402b82-3e4b-4f93-8b0e-d066f993c64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-78b26aa002']</value>
      <webElementGuid>31842790-ed28-423b-94da-a2bc08bc7fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-78b26aa002']/div/a</value>
      <webElementGuid>0b6ab270-150a-4616-9e6d-834336487cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNEXION'])[1]/following::a[1]</value>
      <webElementGuid>997520b5-a026-4c49-8e72-25e63b20ab07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHWARZKOPF PROFESSIONAL'])[1]/preceding::a[1]</value>
      <webElementGuid>3802e3e4-38f7-413c-8fcb-b8dc47fa7441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fr/fr/bienvenue/enregistrer.html')]</value>
      <webElementGuid>9f186712-b3bf-4028-88ed-0ec117518715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-calltoaction[2]/div/div/a</value>
      <webElementGuid>0b951988-4b5b-4aa9-a489-991c479b43eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-78b26aa002' and @href = '/fr/fr/bienvenue/enregistrer.html' and (text() = concat(&quot;
          
          S&quot; , &quot;'&quot; , &quot;ENREGISTRER
      &quot;) or . = concat(&quot;
          
          S&quot; , &quot;'&quot; , &quot;ENREGISTRER
      &quot;))]</value>
      <webElementGuid>985fd5f2-64cd-4f00-b7f6-c75b03613778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
