<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EXPLORER</name>
   <tag></tag>
   <elementGuidId>3d72e1f0-0d26-44f2-83ec-7a8711316f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='calltoaction-12f7416af0'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cbc8b68-c189-4186-a01e-8d8ad38c0f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-12f7416af0</value>
      <webElementGuid>931e76a8-d589-4cad-b5f7-109aaafacd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>customizations__calltoaction</value>
      <webElementGuid>6d32385f-7946-462b-9ea1-9b75b25dd618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta</value>
      <webElementGuid>56f95268-570c-4532-8121-ecef9205fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr/fr/catalogue/courses.html/course/1350093/Test%20Paid%20Online%20Seminar</value>
      <webElementGuid>d40d16c8-563d-420b-a077-3a59e3f8f230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>19b0aca6-d312-4ac3-878f-84ab4b58748c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;_self&quot;}</value>
      <webElementGuid>9697a5bc-6349-4b87-9536-5011067812a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>d90319c6-4330-46d0-bb4b-425f65ed768c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              
              EXPLORER
            </value>
      <webElementGuid>f1407e6d-d69d-483c-bf79-63db34e17ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teaserlist-b7ef794e35&quot;)/ul[@class=&quot;teaserlist__items atomic--target
                teaserlist__items--loadMore&quot;]/li[@class=&quot;teaserlist__item&quot;]/div[@class=&quot;xf-content-height&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/heliux-section[@class=&quot;section container responsivegrid container-max-grid margin-top-small margin-left-small margin-right-small margin-bottom-big aem-GridColumn aem-GridColumn--default--12&quot;]/div[@id=&quot;section-f3e2f0e6fe&quot;]/section[@class=&quot;columncontrol container responsivegrid container-max alignment-vertical-top order-default-mobile alignment-horizontal-left margin-top-default margin-left-default margin-right-default margin-bottom-default default-margin-top default-margin-left&quot;]/div[@id=&quot;columncontrol-39e0c3d3a1&quot;]/heliux-grid[1]/div[@class=&quot;columncontrol__wrapper&quot;]/heliux-calltoaction[@class=&quot;calltoaction button margin-top-default margin-left-none margin-right-none margin-bottom-none calltoaction__animationsbuttonaccent1 isOffScreen isOnScreen&quot;]/div[@id=&quot;wrapper-calltoaction-12f7416af0&quot;]/div[@class=&quot;calltoaction__background&quot;]/a[@id=&quot;calltoaction-12f7416af0&quot;]</value>
      <webElementGuid>55f9b00f-9111-498e-ae8f-a65e0f523688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='calltoaction-12f7416af0'])[2]</value>
      <webElementGuid>f3b7f6e4-fed3-4c37-8321-319ba0a5469d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='wrapper-calltoaction-12f7416af0']/div/a)[2]</value>
      <webElementGuid>1683740d-75ff-4d77-811f-e8a267351e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[2]/following::a[1]</value>
      <webElementGuid>d82b5a93-6199-4933-8e84-81215edae6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★'])[20]/following::a[1]</value>
      <webElementGuid>0df2682a-3d96-465f-9a31-0c029d40e9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A son propre rythme'])[1]/preceding::a[2]</value>
      <webElementGuid>371827a7-4f57-4ff7-841c-53c9c851fd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/fr/fr/catalogue/courses.html/course/1350093/Test%20Paid%20Online%20Seminar')])[2]</value>
      <webElementGuid>66f2d401-b4df-4612-8c7e-aed89d451c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/heliux-section/div[3]/section[2]/div/heliux-grid/div[2]/heliux-calltoaction/div[2]/div/a</value>
      <webElementGuid>b95c5a1c-5dff-4208-912a-0810aed19b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-12f7416af0' and @href = '/fr/fr/catalogue/courses.html/course/1350093/Test%20Paid%20Online%20Seminar' and (text() = '
              
              EXPLORER
            ' or . = '
              
              EXPLORER
            ')]</value>
      <webElementGuid>963233cc-9e63-4781-ad3e-2031c9307584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
