<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JD</name>
   <tag></tag>
   <elementGuidId>ba495d29-39bd-425a-84b2-e584f73fdf07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login__circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f90a14fb-2b3a-41e7-89f1-b3b595119862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__circle</value>
      <webElementGuid>f164b2ba-79d7-4e07-af90-9d356292b408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JD</value>
      <webElementGuid>99d920ba-3d2f-4707-8f69-fdca252c12a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login1667733523206&quot;]/button[@class=&quot;login__button login__button--logout cta&quot;]/div[@class=&quot;login__circle&quot;]</value>
      <webElementGuid>e0f8295b-511c-47f2-a161-c20bcdb87b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button[2]/div</value>
      <webElementGuid>b84d3123-19ee-4182-844d-35fdf33bac5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[1]/following::div[23]</value>
      <webElementGuid>0447f64f-23e1-4b23-b2b6-c1b7a42dbdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compte de John'])[1]/preceding::div[3]</value>
      <webElementGuid>8a606bf6-9227-4e98-aabc-4898a1932f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>24f61f79-0251-4750-adc5-d9b84d3d44d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'JD' or . = 'JD')]</value>
      <webElementGuid>533f2086-621a-4663-84dd-7b02160f6105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
