<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Logout Started FR</name>
   <tag></tag>
   <elementGuidId>8f60cb82-50b6-4994-b54a-61609628fbae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.heading4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification_message_cdc_logout_started']/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>841a3dea-47b8-4a0b-a439-94b1dcc5934e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading4</value>
      <webElementGuid>95d65aa2-cff2-466e-ab9d-a74072d65ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout Started FR</value>
      <webElementGuid>8375e75a-f754-4258-9b10-a60caab9a3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_message_cdc_logout_started&quot;)/div[@class=&quot;notifications__inner&quot;]/h2[@class=&quot;heading4&quot;]</value>
      <webElementGuid>786dc069-7742-461a-997e-3078055a4bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_message_cdc_logout_started']/div[2]/h2</value>
      <webElementGuid>d10ebc0c-a565-4609-9c4f-9b15d8587584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close the notifications'])[1]/following::h2[1]</value>
      <webElementGuid>dfa86227-e453-4c65-b75c-246b8a9dcbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[2]/following::h2[1]</value>
      <webElementGuid>042285ff-fb15-4982-829d-f5cc94283085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPRENDRE ET PROGRESSER'])[1]/preceding::h2[1]</value>
      <webElementGuid>9b6caa1c-03a7-4af6-b375-ea23c1011d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monter en compétences'])[1]/preceding::h2[1]</value>
      <webElementGuid>f5267e87-345f-4f83-a78f-821f6c62aa4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout Started FR']/parent::*</value>
      <webElementGuid>933a2495-88d6-4460-86bf-a10eb3938a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2d287482-7fce-4664-b657-693dbfad6348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Logout Started FR' or . = 'Logout Started FR')]</value>
      <webElementGuid>6c145ac8-f2dc-4d9a-82ef-71a7964bc15e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
