<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CONFIRMER</name>
   <tag></tag>
   <elementGuidId>c90ad3d2-8781-426d-8a8c-619b4818dc29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn__deleteuser-1eafeebfbb > span.calltoaction__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn__deleteuser-1eafeebfbb']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfff7b0d-57a0-4c1f-b31f-575d667bdc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__text</value>
      <webElementGuid>9b2a6e64-697e-4f9c-aa47-40066bacc647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONFIRMER </value>
      <webElementGuid>f3c6609a-f9c6-48e1-8b7e-9f14ad83aacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn__deleteuser-1eafeebfbb&quot;)/span[@class=&quot;calltoaction__text&quot;]</value>
      <webElementGuid>48aa0405-0227-4eea-87df-9a802c7d68cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn__deleteuser-1eafeebfbb']/span</value>
      <webElementGuid>b945a102-15dc-49bb-b09a-eca485399964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTES POUR LES RÉSIDENTS DES ÉTATS-UNIS'])[1]/following::span[2]</value>
      <webElementGuid>2b1097df-58c9-482b-b076-db645feed79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANNULER'])[1]/preceding::span[1]</value>
      <webElementGuid>5d99e2ea-08f8-4719-bcff-77747adaf8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONFIRMER']/parent::*</value>
      <webElementGuid>bf3008eb-a72e-4b95-86ff-5508357288af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/heliux-grid/div/heliux-calltoaction/div[2]/div/button/span</value>
      <webElementGuid>15963062-1097-4ea3-9a73-4abfb785be9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CONFIRMER ' or . = 'CONFIRMER ')]</value>
      <webElementGuid>10b08198-0125-4010-80b4-d02175fb140a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
