<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , ELearningCP_fluidicPla_2bd6db</name>
   <tag></tag>
   <elementGuidId>1b741a22-d391-47f9-b5dd-e3f0db195c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ELearningCP_fluidicPlayer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ELearningCP_fluidicPlayer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b01047c6-4c6b-48a8-8eb8-0fcac494b098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ELearningCP_fluidicPlayer</value>
      <webElementGuid>1292b204-cef3-419b-b2bc-84d33cb1bc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>971</value>
      <webElementGuid>8118f2d5-d834-4815-8a9e-89fc8d55f741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1792</value>
      <webElementGuid>3f74fb96-8b07-478e-a631-74cefc417dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://learningmanagereu.adobe.com/app/player?access_token=7656614d0fd73e971a6d10c3cd636847&amp;trapfocus=true&amp;lo_id=course:1350094&amp;module_id=course:1350094_1409619_1644477_0</value>
      <webElementGuid>a44368f8-8aee-4c01-90aa-05ba82f670a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ELearningCP_fluidicPlayer&quot;)</value>
      <webElementGuid>f3ebba78-6e63-41d8-bfdf-25cc9e74ad2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ELearningCP_fluidicPlayer']</value>
      <webElementGuid>30315e2f-d958-473c-b4b4-93a27cf0a65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>db269cf3-ac47-4e24-a9e7-0de3f205a853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ELearningCP_fluidicPlayer' and @src = 'https://learningmanagereu.adobe.com/app/player?access_token=7656614d0fd73e971a6d10c3cd636847&amp;trapfocus=true&amp;lo_id=course:1350094&amp;module_id=course:1350094_1409619_1644477_0']</value>
      <webElementGuid>a8a13ef3-8381-4d74-8ad8-eeba29969a0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
