<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Stay in control of compliance_modulePlayerIframe</name>
   <tag></tag>
   <elementGuidId>b1110faa-2384-482a-84b2-26aaa588d1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='modulePlayerIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modulePlayerIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5f510183-b436-4ed5-9edc-e321deaa4481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://learningmanagereu.adobe.com//app/videoplayer?videoId=6212420952001&amp;device=false&amp;ios=undefined&amp;context=formal&amp;asset_id=1414527&amp;asset_type=resource&amp;auth_token=7656614d0fd73e971a6d10c3cd636847</value>
      <webElementGuid>977b9118-21bb-4f1c-bc9b-e4f5e575ef95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modulePlayerIframe</value>
      <webElementGuid>6d615262-4f9e-4a13-9371-2461c072ca26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modulePlayerIframe</value>
      <webElementGuid>d65df6da-6142-483e-bbac-97f23bf84403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay *</value>
      <webElementGuid>5eeb7f96-5b99-4f0e-b217-43ef420d9c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Module Player</value>
      <webElementGuid>8ddaf641-a38c-4ed3-a86e-5b0a4ccb51e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modulePlayerIframe&quot;)</value>
      <webElementGuid>93706671-396d-44fb-8a7a-e9d9f9823716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_E-Learning Course Page  Test Paid Self Paced/iframe_concat(id(, , ELearningCP_fluidicPla_2bd6db</value>
      <webElementGuid>a73258e5-4065-4614-90d7-b32fb81e138a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='modulePlayerIframe']</value>
      <webElementGuid>d04f7df3-6dd5-4a26-857b-58cd63562473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modulePlayerDiv']/iframe</value>
      <webElementGuid>c0f822db-8855-4149-ad5a-b46f731ffd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>98bf32e4-d428-4628-9cb2-2e036312953f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://learningmanagereu.adobe.com//app/videoplayer?videoId=6212420952001&amp;device=false&amp;ios=undefined&amp;context=formal&amp;asset_id=1414527&amp;asset_type=resource&amp;auth_token=7656614d0fd73e971a6d10c3cd636847' and @id = 'modulePlayerIframe' and @name = 'modulePlayerIframe' and @title = 'Module Player']</value>
      <webElementGuid>e3f4adf5-de82-47c1-b0c4-f40bb736143a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
