<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_COMMENCER</name>
   <tag></tag>
   <elementGuidId>fe1d7258-f73e-4383-b28d-f2b92cac0a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn__calltoaction-76b5ff60ef']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn__calltoaction-76b5ff60ef > span.calltoaction__text.calltoaction__text--initial.calltoaction__text--initial-only</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5de4316-2935-4269-ad1c-732ee7f445e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__text calltoaction__text--initial calltoaction__text--initial-only</value>
      <webElementGuid>b8a675d1-85c8-4b0e-9099-c8ba454d1d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMMENCER</value>
      <webElementGuid>c0e67852-f124-42bb-8633-4baa0a34717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn__calltoaction-76b5ff60ef&quot;)/span[@class=&quot;calltoaction__text calltoaction__text--initial calltoaction__text--initial-only&quot;]</value>
      <webElementGuid>073ae88c-cda4-41cc-9390-45b59c0d1e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn__calltoaction-76b5ff60ef']/span</value>
      <webElementGuid>28146565-728b-40a1-b0c2-e01ba42dc525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En cours'])[1]/following::span[1]</value>
      <webElementGuid>fcdccc94-b3cf-43e6-a4f4-591d47852724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vous êtes inscrit à ce cours'])[1]/following::span[1]</value>
      <webElementGuid>c8464fea-a7c5-46a9-98d2-13f1428c2d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COMMENCER']/parent::*</value>
      <webElementGuid>dde8a0fd-2976-4e16-b49d-bd2cb8e3b064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/heliux-calltoaction/div[2]/div/button/span</value>
      <webElementGuid>3f599944-80b6-479a-b53f-a3f272360cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'COMMENCER' or . = 'COMMENCER')]</value>
      <webElementGuid>a7592b14-edb9-4efd-a92f-9bcf03aab6b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
