<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Video Player is loading_ACAPSimplePlayer_html5_api</name>
   <tag></tag>
   <elementGuidId>9d37ee29-ad6d-47b1-b025-846c1bd3a496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='ACAPSimplePlayer_html5_api']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ACAPSimplePlayer_html5_api</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>67819c10-c7d7-4196-a3de-96c8581c65dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ACAPSimplePlayer_html5_api</value>
      <webElementGuid>c6b2de5b-7b24-46c9-9973-fa834e3665eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-account</name>
      <type>Main</type>
      <value>2890187661001</value>
      <webElementGuid>7fdc6772-3c9c-4e6c-8ec5-e65fec21e927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-player</name>
      <type>Main</type>
      <value>YefW6AINQ</value>
      <webElementGuid>d077c8cd-f71e-4323-95b8-1b702135ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-embed</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>bf914c32-5830-4c1f-9e23-3623962be3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>799474ee-b31a-4a60-b2d2-4fe298ff1601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>playsinline</name>
      <type>Main</type>
      <value>playsinline</value>
      <webElementGuid>a98fd0bb-90c0-465c-8eed-6f0959df1774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>7e3e42dc-2ad6-4044-9970-ae0a7a592580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d617df78-b885-4875-a540-eb1b720e2a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e48f41ee-c52f-48b1-97be-d2ac678808dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://cpcontents.adobe.com/ac70adf0-2cf7-4f2f-af29-56f4c1a6c19d</value>
      <webElementGuid>188bfe7e-9a46-4723-a499-5f4e70aa7f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACAPSimplePlayer_html5_api&quot;)</value>
      <webElementGuid>0e646548-36fe-41c5-8044-f9d644f12700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_E-Learning Course Page  Test Paid Self Paced/iframe_Stay in control of compliance_modulePlayerIframe</value>
      <webElementGuid>29685714-d6b1-4196-8c73-a37e8194dcbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='ACAPSimplePlayer_html5_api']</value>
      <webElementGuid>e982b6cf-2e7e-4140-88ba-174e70227457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ACAPSimplePlayer']/video</value>
      <webElementGuid>b2e38f62-3a4c-494a-9157-a026b4cfa9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>783abb0d-050e-40db-af97-4ed9afb4d0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'ACAPSimplePlayer_html5_api' and @src = 'blob:https://cpcontents.adobe.com/ac70adf0-2cf7-4f2f-af29-56f4c1a6c19d']</value>
      <webElementGuid>1eaaa7a1-fd7a-4feb-8a08-b725eb1e0379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
