<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mr</name>
   <tag></tag>
   <elementGuidId>f32cee57-62a6-4dc2-83d7-3553fb4e85ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.formoptions__itemLabel > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-options-677655452']/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5337e619-9c57-4ffd-8dad-aedc6890a0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>user.salutation__mr__form-options-677655452</value>
      <webElementGuid>b5da0fb3-4c3f-4ae7-8c47-802e1bc633ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mr.</value>
      <webElementGuid>8f1beb95-a5ec-44a4-80e6-dcfc874e8c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-options-677655452&quot;)/div[@class=&quot;formoptions__item&quot;]/span[@class=&quot;formoptions__itemLabel&quot;]/label[1]</value>
      <webElementGuid>591f2ced-351e-4641-a99a-20fdc087292b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-options-677655452']/div/span/label</value>
      <webElementGuid>14ce3b63-c72e-41da-9cf0-c73e1e9f1e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salutation'])[1]/following::label[1]</value>
      <webElementGuid>384d21f8-74c0-41ef-ba0a-0d4cb423e6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address *'])[1]/following::label[2]</value>
      <webElementGuid>5ca8c6ee-b3cf-4b61-907a-033386b7de1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ms.'])[1]/preceding::label[1]</value>
      <webElementGuid>ecf9d23d-117e-4d20-8b20-674a8749aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mx.'])[1]/preceding::label[2]</value>
      <webElementGuid>20905dcd-4f35-4e47-af20-207479081aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mr.']/parent::*</value>
      <webElementGuid>dc2fce9a-90dd-40b8-b6ac-c65bc2022461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>5f5d595b-fe29-4e8a-a86f-867aa904a922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Mr.' or . = 'Mr.')]</value>
      <webElementGuid>d6d615c5-4aec-4535-924c-b06450d4c9ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
