<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vous avez oubli votre mot de passe</name>
   <tag></tag>
   <elementGuidId>f5d179a5-fc37-4084-a7bb-8baecd194675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-login-form']/div[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-login-form > div.gigya-layout-row > a.gigya-composite-control.gigya-composite-control-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90ca23ff-6599-4679-96ab-8022db2e21bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-switch-screen</name>
      <type>Main</type>
      <value>gigya-forgot-password-screen</value>
      <webElementGuid>68617f16-1ded-4a29-b8af-8204bd2342d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-composite-control gigya-composite-control-link</value>
      <webElementGuid>fd7369ef-9685-4430-a357-2dbea995e5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2cf55730-2461-49c7-b69b-bdca6a3e9ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>LINK_25567572436694244_LABEL</value>
      <webElementGuid>a15c7614-51f0-44f1-82ad-307a2451eece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_45_1673219579443</value>
      <webElementGuid>5c9d147e-a4c3-4cb7-ba58-361054d68203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fbf4afc-585e-4caf-8da1-8dc631896e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>template,template,instance,instance,instance</value>
      <webElementGuid>a021ce28-ab83-414f-b646-1270111593f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c926701d-9f52-43f6-ab7b-dcf7753aebcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>776cb452-f24c-4224-b937-4696eaccd0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25cc6da6-7792-4bf7-9cab-3c72cc22ad18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vous avez oublié votre mot de passe ?</value>
      <webElementGuid>0e94e8ea-5801-40be-ab95-e79ad0fcb2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vous avez oublié votre mot de passe ?</value>
      <webElementGuid>f8ada9a5-ac01-4729-9d7d-322481ee450d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-login-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/a[@class=&quot;gigya-composite-control gigya-composite-control-link&quot;]</value>
      <webElementGuid>57a5906b-6560-4b49-a37a-ca5b7eaec04f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-login-form']/div[5]/a</value>
      <webElementGuid>b91c474b-6fe2-47a2-81ac-e579483d3c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vous avez oublié votre mot de passe ?')]</value>
      <webElementGuid>e8707a97-0992-4b61-8d6a-500bced7b98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe'])[1]/following::a[1]</value>
      <webElementGuid>6b4db25c-c62e-4d90-ae73-f1a39a9ca61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/following::a[1]</value>
      <webElementGuid>3fe300b7-2840-404e-befe-8384733e6ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUIVEZ-NOUS'])[1]/preceding::a[1]</value>
      <webElementGuid>8f517162-d46e-4e6a-bfa5-7a2ea2caf13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENTIONS LÉGALES'])[1]/preceding::a[6]</value>
      <webElementGuid>56fb684d-9fec-4307-b91c-44a8bdeb3f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vous avez oublié votre mot de passe ?']/parent::*</value>
      <webElementGuid>b2b838bd-0158-42a2-93d6-6f919841f7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>bc163948-ae82-41ae-9481-368916ea1681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[5]/a</value>
      <webElementGuid>3ee6e6a6-a87e-4e6d-a02a-0edd90e13f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'Vous avez oublié votre mot de passe ?' and (text() = 'Vous avez oublié votre mot de passe ?' or . = 'Vous avez oublié votre mot de passe ?')]</value>
      <webElementGuid>67d6c8d7-1d71-45f9-a9e7-2b651e1470c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
