<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identifiant ou mot de passe non valide</name>
   <tag></tag>
   <elementGuidId>1ab9173d-0564-49a5-89c4-e1a45443a3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-login-form']/div[6]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gigya-error-msg.gigya-form-error-msg.gigya-error-code-403042.gigya-error-msg-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab76cac6-d94d-4f6e-a214-39148d7523f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-error-msg gigya-form-error-msg gigya-error-code-403042 gigya-error-msg-active</value>
      <webElementGuid>3461d678-dde8-4052-bf8f-42513bb296b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bound-to</name>
      <type>Main</type>
      <value>gigya-login-form</value>
      <webElementGuid>ef279b19-26ca-4d9a-9542-34477e403720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_41_1676895373542</value>
      <webElementGuid>0355f7b1-44aa-4c42-a29e-65343a2ec68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>766815e3-3091-4a53-9b64-f543a28cdb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>6e487891-7b3e-4fdf-a14e-512a08e161a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e664e99-e068-4045-ab57-a46b9d58c9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8db199cc-fc90-4912-9b30-be2b9bcf23cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identifiant ou mot de passe non valide</value>
      <webElementGuid>3fe76931-4563-4098-91c9-7df9044aa697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-login-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-error-display gigya-composite-control gigya-composite-control-form-error gigya-error-code-403042 gigya-error-display-active&quot;]/div[@class=&quot;gigya-error-msg gigya-form-error-msg gigya-error-code-403042 gigya-error-msg-active&quot;]</value>
      <webElementGuid>6e9a4be5-7088-4b1e-bee7-873cb9cf32c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-login-form']/div[6]/div[2]/div</value>
      <webElementGuid>6e65115b-e9ba-4f53-a9a9-a5b60f1b7314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vous avez oublié votre mot de passe ?'])[1]/following::div[5]</value>
      <webElementGuid>649e8ae5-c846-4d0b-b8b3-aa1eb275ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe'])[1]/following::div[6]</value>
      <webElementGuid>36a52977-535c-4cbb-a689-6059b78bc03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUIVEZ-NOUS'])[1]/preceding::div[2]</value>
      <webElementGuid>1413d54a-662c-4c6d-9ebd-682bd2d78d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MENTIONS LÉGALES'])[1]/preceding::div[21]</value>
      <webElementGuid>2add0fee-354c-4b73-8a6a-95acf488f7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identifiant ou mot de passe non valide']/parent::*</value>
      <webElementGuid>d5e01362-2670-4194-be12-01dce4b3d947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[6]/div[2]/div</value>
      <webElementGuid>59cde119-a468-4cdc-927b-682fb1f6f2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Identifiant ou mot de passe non valide' or . = 'Identifiant ou mot de passe non valide')]</value>
      <webElementGuid>b618dcaa-7bdb-4ccf-a043-73ba4fc1c020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
