<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Interests, skills and knowledgeStartYou can quit anytime and Continue later</name>
   <tag></tag>
   <elementGuidId>8fd7ee31-cc8b-42d5-88f1-c99eec9bbace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pf-root']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pf__welcomeScreen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bac253dd-8071-41b8-be90-30ca7a0bb3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf__welcomeScreen</value>
      <webElementGuid>2458e975-26d9-47fe-a830-17e181c7ef66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interests, skills and knowledgeStartYou can quit anytime and Continue later</value>
      <webElementGuid>3c503019-8eaf-41b2-97a3-8efc810d4079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pf-root&quot;)/div[@class=&quot;pf__app&quot;]/div[@class=&quot;pf__wrapper&quot;]/div[@class=&quot;pf__formWrapper&quot;]/div[1]/div[@class=&quot;pf__welcomeScreen&quot;]</value>
      <webElementGuid>c9980689-ac55-41d4-b423-b4118f1bd463</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pf-root']/div/div/div/div/div</value>
      <webElementGuid>f1e58ae4-4fb4-4205-a429-5e255c129eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTES POUR LES RÉSIDENTS DES ÉTATS-UNIS'])[1]/following::div[26]</value>
      <webElementGuid>2bbe0036-d69c-488a-a1a3-1684c6e96514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLITIQUE DE COOKIES'])[1]/following::div[27]</value>
      <webElementGuid>2b72665c-a85b-40e9-a0fd-e594912174d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>e2c37321-23b4-4043-b0cc-2396648e30fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later' or . = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later')]</value>
      <webElementGuid>0919b8a2-67d1-442b-80c8-df5d1ad952f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
