<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Merci daccepter les cookies pour bnfici_96c076</name>
   <tag></tag>
   <elementGuidId>152c7cd8-8d86-4c51-ac1a-02f9f33fb13d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onetrust-group-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-group-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f9cb3fc-e4df-49ca-bfc4-912b176ff3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-group-container</value>
      <webElementGuid>644e404c-791e-4b9b-bd10-2738b239a321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ot-sdk-twelve ot-sdk-columns</value>
      <webElementGuid>3c853f2c-db72-499b-8df7-feee788b298b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merci d’accepter les cookies pour bénéficier de toute l’expérienceEn cliquant sur « Autoriser tous les cookies », vous consentez à l’usage des cookies. Ils nous permettent d’améliorer la navigation, analyser vos usages du site et vous proposer une expérience personnalisée. À tout moment, vous pouvez vous informer plus en détail sur les types de cookies en consultant notre déclaration de protection des données, disponible en pied de page de notre site.</value>
      <webElementGuid>35f7f054-b00a-4ea5-bbb9-19629fa1c4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-group-container&quot;)</value>
      <webElementGuid>129d8f62-8255-4cef-86eb-b0a523ffcf2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onetrust-group-container']</value>
      <webElementGuid>14eeb81d-2cd6-4627-8632-60dc962bac46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-banner-sdk']/div/div/div</value>
      <webElementGuid>79110fc9-1c9e-4f9a-9886-6a6f43b651b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTES POUR LES RÉSIDENTS DES ÉTATS-UNIS'])[1]/following::div[17]</value>
      <webElementGuid>44d7e095-0a2b-466f-90fe-c38a43c122b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLITIQUE DE COOKIES'])[1]/following::div[18]</value>
      <webElementGuid>80aa7e8d-15b5-4bd4-b481-9bd0b1632930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout refuser'])[1]/preceding::div[4]</value>
      <webElementGuid>9d6b7a4b-a0f6-4fe4-b894-02a55480ac5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div</value>
      <webElementGuid>1d11fb0b-075f-47bc-a38d-35ab22523665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onetrust-group-container' and (text() = 'Merci d’accepter les cookies pour bénéficier de toute l’expérienceEn cliquant sur « Autoriser tous les cookies », vous consentez à l’usage des cookies. Ils nous permettent d’améliorer la navigation, analyser vos usages du site et vous proposer une expérience personnalisée. À tout moment, vous pouvez vous informer plus en détail sur les types de cookies en consultant notre déclaration de protection des données, disponible en pied de page de notre site.' or . = 'Merci d’accepter les cookies pour bénéficier de toute l’expérienceEn cliquant sur « Autoriser tous les cookies », vous consentez à l’usage des cookies. Ils nous permettent d’améliorer la navigation, analyser vos usages du site et vous proposer une expérience personnalisée. À tout moment, vous pouvez vous informer plus en détail sur les types de cookies en consultant notre déclaration de protection des données, disponible en pied de page de notre site.')]</value>
      <webElementGuid>5d660be8-63a7-4a46-b9af-bec2bd11eef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can quit anytime and Continue later'])[1]/following::div[11]</value>
      <webElementGuid>c428d3f0-9ea2-4b7a-b265-b17cb702ebe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::div[11]</value>
      <webElementGuid>7492f9da-2856-43ee-bea9-16d832ce55e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout refuser'])[1]/preceding::div[5]</value>
      <webElementGuid>b1e9f5b7-291e-45d3-b85f-034e5a42fb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/div</value>
      <webElementGuid>7dde5462-b61a-47a1-a917-7ac97bc55cff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
