<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NOTES POUR LES RSIDENTS DES TATS-UNIS_modal__overlay</name>
   <tag></tag>
   <elementGuidId>b7b29289-4289-4ef6-a586-14e9e94df8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal__overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='modal__base']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e39daea-0f29-4b35-a0e4-400ae92713de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal__overlay</value>
      <webElementGuid>84174981-df18-490d-b52b-b99ccf2f1759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-5bf31f6047e4718e1299e9c1f655573f7c74fb2a0b42fa4e6b4f332e6875ad02&quot;)/div[@class=&quot;popup__modal&quot;]/div[@class=&quot;modal__base&quot;]/div[@class=&quot;modal__overlay&quot;]</value>
      <webElementGuid>5a440c32-3736-4d19-8b6e-55fe8ea9a688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-5bf31f6047e4718e1299e9c1f655573f7c74fb2a0b42fa4e6b4f332e6875ad02']/div/div/div</value>
      <webElementGuid>4f0fb2d8-c1d3-45cf-8fa0-cfc164873d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div</value>
      <webElementGuid>0dd95f6a-18ac-423a-a53a-bb9d5d5620b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
