<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vous avez oubli votre mot de passe_gigya-input-submit</name>
   <tag></tag>
   <elementGuidId>c36581af-28ef-4c56-ab16-023a55fd2cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SE CONNECTER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gigya-login-form > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-submit > input.gigya-input-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82b9646c-2170-4d3a-93b2-f2230a57f2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>819d3e3d-056c-44bb-bb9a-2eaf185ebc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-submit</value>
      <webElementGuid>18245e51-5137-4885-b0a3-7da638887723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1be789c9-5173-47a7-a0d9-68fbf3951102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ff3ef422-0aaa-4dc2-a24d-7f5c9e7d74e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:value</name>
      <type>Main</type>
      <value>screenset.translations['SUBMIT_49569983559348300_VALUE']</value>
      <webElementGuid>1084c874-e3fa-411c-8707-12ab8a958152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_42_1673130212467</value>
      <webElementGuid>03e041f5-125c-4800-a8c8-cacda2fbba0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>282e9854-94c4-4713-bfc0-8baefcdd85f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>27c1723a-6580-43fd-91f6-d323ecf3d728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SE CONNECTER</value>
      <webElementGuid>2dcf7dde-9ad8-4fb8-baeb-8736efa475ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-login-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-submit&quot;]/input[@class=&quot;gigya-input-submit&quot;]</value>
      <webElementGuid>f31a94a1-055c-4287-be18-2bd2d7f8b0a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SE CONNECTER']</value>
      <webElementGuid>430bc027-5048-4006-933b-5e2955287773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-login-form']/div[6]/div/input</value>
      <webElementGuid>c40531ce-41be-4650-a490-7977a9c3bac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[6]/div/input</value>
      <webElementGuid>4084b145-63b8-4256-8d78-9c20f3dae45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>b4a4899e-4d0e-4a73-a08d-a465ccba34ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
