<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_passwordRetype</name>
   <tag></tag>
   <elementGuidId>84ae7fa4-8299-4c55-aedb-fde34f7bdbf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-password-150863629148784450</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-password-150863629148784450']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>442829ff-2a10-43a4-a36d-5a97d3c3f75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ad5e99be-dc23-46eb-bf7f-ed7e0a48cada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-password</value>
      <webElementGuid>b4427e33-59ab-4971-a786-ce0fd4630908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>ab9df7e0-a2de-4f41-8671-8943d74fbc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-conditional:show-password-strength</name>
      <type>Main</type>
      <value>screenset.width &lt; 900?up</value>
      <webElementGuid>495f7512-80c1-4254-ad7e-7f0bdd9962c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordRetype</value>
      <webElementGuid>e009a674-6c7e-4d2e-8054-f905822726f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_150863629148784450_PLACEHOLDER']</value>
      <webElementGuid>8f59decf-505f-4e22-848b-2d3cee1c1a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:aria-label</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_150863629148784450_PLACEHOLDER']</value>
      <webElementGuid>206f23ff-ed41-4194-b52c-792519713bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-password-150863629148784450</value>
      <webElementGuid>002776c0-f687-41ce-a53e-f480f80fc880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a234eb21-36ae-4db6-b15b-d9b791efc9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>017c4c0c-ed68-46ac-86cf-ef732c9735e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-default-show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>ba350ab6-2f44-4d7b-8331-73669cc57631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>passwordRetype</value>
      <webElementGuid>3660d4bc-cf7a-4c9d-95c7-9f4231ac70df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-password-150863629148784450</value>
      <webElementGuid>52b05c84-eed2-46dc-a579-80047a3817dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba83effd-c162-43af-be85-15bc231e6d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>1ba6eecf-0231-459c-8846-cf6a978b6d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password *</value>
      <webElementGuid>fc92aff0-d2f7-4acc-94ce-a6b1fefc6904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>ec8a11ed-d668-412d-b8b7-5d2cafa4c44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-password-150863629148784450&quot;)</value>
      <webElementGuid>3204376f-5bdc-4bfa-b594-086ac654019f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-password-150863629148784450']</value>
      <webElementGuid>2e046b74-8ec8-4c09-bf9b-49ed5975da5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[6]/input</value>
      <webElementGuid>fc99e54c-998e-4cd1-a4ce-abb4dc22903e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[6]/input</value>
      <webElementGuid>0fba6550-4622-4995-a13d-1b9bfc084696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'passwordRetype' and @id = 'gigya-password-150863629148784450' and @placeholder = 'Confirm Password *']</value>
      <webElementGuid>a2929b2b-0164-4ab2-ab73-756af774f5ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
