<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_preferences.terms.HenkelLifeTimeToS.isConsentGranted</name>
   <tag></tag>
   <elementGuidId>e92234e4-c007-4a78-8bbf-f058a37a400f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-72004138349937020</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-72004138349937020']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14369f60-0027-49ea-abec-9c9f13176faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7c2180a-20e0-4aab-86fa-3121e92fc6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>64f6d894-e95d-4812-ae00-27f5314fb481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelLifeTimeToS.isConsentGranted</value>
      <webElementGuid>b711f8cd-2ea1-4c15-b067-9993e1c3b9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>c815de3a-92a2-4dca-b4c6-4db4d1cb90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-72004138349937020</value>
      <webElementGuid>126ccae7-af73-43b4-8b69-2ab663bc8fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1258fb3-be6a-40f3-b799-80205bba399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>626b4aef-26f4-48c5-a9cf-cae15464c388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelLifeTimeToS.isConsentGranted</value>
      <webElementGuid>056291eb-24d0-49d6-a0b6-f392d028ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>989bc025-0119-4451-86c3-c06b70d80604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-72004138349937020</value>
      <webElementGuid>c498ee6e-245c-4aeb-a8cf-39cd96dda529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70f585c1-3efb-4ab7-b0d3-c88b6b708ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-72004138349937020&quot;)</value>
      <webElementGuid>f3be5458-b192-4e60-bff3-c8d675345e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-72004138349937020']</value>
      <webElementGuid>76745948-b57c-466b-887c-d97db394f86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/input</value>
      <webElementGuid>a3aa25fa-63d8-4345-8ee4-7dc8525dabb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[8]/input</value>
      <webElementGuid>616c63e4-e734-41a9-b63e-d28d749cf9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'preferences.terms.HenkelLifeTimeToS.isConsentGranted' and @checked = 'checked' and @id = 'gigya-checkbox-72004138349937020']</value>
      <webElementGuid>cda0237a-964d-41da-9bcf-ed1d632802ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
