<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indicates a required field_gigya-input-submit</name>
   <tag></tag>
   <elementGuidId>cac2eb51-c93e-4a89-904d-c594662196a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-lite-account-progression-form > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-submit > input.gigya-input-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Join our community now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>272ee3d1-d91b-48f3-9f4e-7594c3eaadaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80757228-27f0-41f4-aa1f-79ed8cec5c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-submit</value>
      <webElementGuid>954f89f4-d315-4335-a87d-ae495c320b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9822e267-34af-4c9c-afd0-8b2bb2afdd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ac94f33a-0076-4ef2-84f4-55d873174b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:value</name>
      <type>Main</type>
      <value>screenset.translations['SUBMIT_38434659033546610_VALUE']</value>
      <webElementGuid>4eadcc35-b815-469b-83b1-410dc1c1292b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_40_1676972646877</value>
      <webElementGuid>7de3b9f0-dd55-4082-865c-12bc789994bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32a09fac-0a1d-40b6-9a48-ae1fa1f31739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>9255bc35-d1d3-41cb-946a-bef478dbc0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Join our community now</value>
      <webElementGuid>21a1a816-753c-4444-82cb-6dcbaccbe413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-lite-account-progression-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-submit&quot;]/input[@class=&quot;gigya-input-submit&quot;]</value>
      <webElementGuid>84dc4340-edf8-4363-adcb-b1a0d84c3ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Join our community now']</value>
      <webElementGuid>d79db248-8af3-44d0-ac6c-c84b5b897ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[9]/input</value>
      <webElementGuid>3fd9b07c-6c04-4e8a-a5fe-87110ebf0a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[9]/input</value>
      <webElementGuid>a6509d9e-fe08-4011-a415-fd1d8ac0e1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>8378497d-0200-4868-911a-b817e58d819f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
