<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_password</name>
   <tag></tag>
   <elementGuidId>d280b791-0833-4dde-a720-e08c4e3dc9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-password-98020708136770500</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-password-98020708136770500']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11067f1f-2ddc-4ec8-ad91-7d3f94a9a599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f73dbbb0-2a26-4a8a-b030-189c1239aff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-password</value>
      <webElementGuid>f7705fa3-d1a9-45f7-8dfe-3cce7884fa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-conditional:show-password-strength</name>
      <type>Main</type>
      <value>screenset.width &lt; 900?up</value>
      <webElementGuid>f93996d8-a92f-403a-be65-83df0b2dc6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8ee612a0-a601-4f63-adcb-c82dc27eb5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>3ed94eca-af1f-487c-9414-8ad2a2741212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_148905838322575840_PLACEHOLDER']</value>
      <webElementGuid>03281f29-9013-426d-88f0-993fbea9ee1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:aria-label</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_148905838322575840_PLACEHOLDER']</value>
      <webElementGuid>02018c8a-9567-4d55-beda-f7d467421419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-password-98020708136770500</value>
      <webElementGuid>a58123f3-6361-411e-80bf-f3893100bbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e7b5de7-b048-435b-bebd-f57be8e173f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>568c6a6f-e349-45fc-b59b-6945011979e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-default-show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>e674086f-c9b4-45b8-a354-53428b16f8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f86c189a-7db4-452c-abbf-8638af3b82bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-password-98020708136770500</value>
      <webElementGuid>ac0a1447-cbd0-40ed-a6bb-2b892d93217c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54645170-22d6-46f7-b72d-b8223228b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e03911f8-912a-4185-9718-7074989274a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password *</value>
      <webElementGuid>59cc5cb7-8348-4c27-8862-db1c5e995639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>89f61168-ec10-4eb7-ab39-964542844e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-password-98020708136770500&quot;)</value>
      <webElementGuid>ffc7741c-c10c-45fd-ad51-0701c5fac62e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-password-98020708136770500']</value>
      <webElementGuid>ed306247-f229-46e4-a802-15356d6ddb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[5]/input</value>
      <webElementGuid>4d8a82e9-c27d-41cb-a629-e05c3b62f5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[5]/input</value>
      <webElementGuid>176fcbe3-5621-4b8d-9cd3-f4ff0920db70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'gigya-password-98020708136770500' and @placeholder = 'Password *']</value>
      <webElementGuid>482c6aee-c99e-46fe-b4d2-a5b9111a0ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
