<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice</name>
   <tag></tag>
   <elementGuidId>6279887f-766c-4209-8a28-995905f94a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d51caa8-68d1-4467-8a1d-1cb58c31f2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label-text gigya-checkbox-text</value>
      <webElementGuid>4469b983-923a-4141-8898-92cdc6b22e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>CHECKBOX_72004138349937020_LABEL</value>
      <webElementGuid>1ac7e569-081a-429c-9090-143610703cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_47_1676972646878</value>
      <webElementGuid>f3d43901-c9cc-416b-813b-cbb669b68010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>649401bc-32a1-4924-a795-5530fe538890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance,template</value>
      <webElementGuid>cc2509fd-82a7-49ab-a389-77ef5885d089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.</value>
      <webElementGuid>e3ec3de0-a66c-43a4-aab6-87c8433f5f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-lite-account-progression-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-checkbox gigya-terms-valid&quot;]/label[@class=&quot;gigya-label&quot;]/span[@class=&quot;gigya-label-text gigya-checkbox-text&quot;]</value>
      <webElementGuid>ed8e3c98-83d9-431c-b54a-5d1002c73c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/label/span</value>
      <webElementGuid>8518bc18-dcf4-4794-909b-b514c9eebae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::span[7]</value>
      <webElementGuid>7ef7f0b1-462f-4015-9f7f-7ed6b714a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[3]/following::span[10]</value>
      <webElementGuid>1320da3d-65a5-49e5-a574-4fda9863416a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes, I accept the']/parent::*</value>
      <webElementGuid>743c9352-48bc-4f15-a5b6-dd265e405558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[8]/label/span</value>
      <webElementGuid>7566252e-984b-4600-9e7d-688735f64803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.' or . = 'Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.')]</value>
      <webElementGuid>0e70572c-9d36-4c00-ba06-bba40250a845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
