<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Veuillez vrifier votre compte Schwar_c9c7e5</name>
   <tag></tag>
   <elementGuidId>35cf7841-4426-4366-b6ca-156dfb54c8df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeMail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeMail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>341c94e3-2fe7-4047-8a0f-f4a61f971ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeMail</value>
      <webElementGuid>b785373d-332c-41c5-98d8-86807588ea00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 no-padding no-border</value>
      <webElementGuid>549b3de3-f414-439b-a508-ad4f9037e08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.minuteinbox.com/email/id/2</value>
      <webElementGuid>00368329-cda7-4e80-9e83-4cb38b1c3729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this);</value>
      <webElementGuid>59b22b2f-dab5-43ed-9a29-62741c118975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeMail&quot;)</value>
      <webElementGuid>7089c37d-de53-4f57-b9e7-e71108478b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeMail']</value>
      <webElementGuid>b0aee524-42ce-4cc1-b10d-3496f4d03a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textMail']/iframe</value>
      <webElementGuid>5a0a0772-aa9d-4351-ac3c-3683332ab012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>49411dd1-334f-440f-a6cc-bbb1229f7f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeMail' and @src = 'https://www.minuteinbox.com/email/id/2']</value>
      <webElementGuid>fd4adb9b-26d5-4dcb-acd1-3061acba97cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
