<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Se dconnecter</name>
   <tag></tag>
   <elementGuidId>a9cb1117-d8a1-4f66-a9ac-80950511ca17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutDropdownLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logoutDropdownLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>394e6395-a0a8-4c62-a921-4f190e4a8678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9e342dbb-e547-402f-9f42-d2a95acf05fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoutDropdownLink</value>
      <webElementGuid>9670fdce-faf2-46f7-9d55-7faedef00819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automationid</name>
      <type>Main</type>
      <value>logoutDropdownLink</value>
      <webElementGuid>e5351b8a-7df8-4538-b1fd-027608bdddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationid</name>
      <type>Main</type>
      <value>component:right-navbar:::action.signOut:::</value>
      <webElementGuid>167fa8be-5342-4779-b44e-5875adee7afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rolesMenuClickable</value>
      <webElementGuid>39e9838e-6dfb-4774-b583-ff2c82f2ac57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ember-action-1889</name>
      <type>Main</type>
      <value>1889</value>
      <webElementGuid>a2db9eaf-b736-4285-8fe8-f42ad897b0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Se déconnecter</value>
      <webElementGuid>c476bdd8-d55d-42c3-ab57-333c67f07d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoutDropdownLink&quot;)</value>
      <webElementGuid>56340cb7-61a6-4607-a5a2-6a93cf5ec187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logoutDropdownLink']</value>
      <webElementGuid>4e533931-880a-4243-bade-b94ea416481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulUserMenuDropdown']/li[6]/ul/li[3]/a</value>
      <webElementGuid>ac674469-1cca-465a-88e3-8e6645d29dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Se déconnecter')]</value>
      <webElementGuid>24975ab6-e3c5-4117-9f61-1ab8c5bc9b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aide'])[1]/following::a[1]</value>
      <webElementGuid>a3f0bf8a-7e65-44c6-89af-e972b83300fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Élève'])[1]/following::a[4]</value>
      <webElementGuid>c1e10bb4-cdbb-4946-a021-8e7f79853d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prise en main'])[1]/preceding::a[1]</value>
      <webElementGuid>9dc55358-4b74-48a3-a148-6e64cf3c9049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPRENTISSAGE'])[1]/preceding::a[2]</value>
      <webElementGuid>ceddb08d-868e-4946-975c-ad1cac5bff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Se déconnecter']/parent::*</value>
      <webElementGuid>da48fc6f-8f3c-4701-96c0-37a0e5892e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>d35cc478-0cb2-4a76-a0bb-01502881c160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[3]/a</value>
      <webElementGuid>85c6d92c-334e-46c3-8e3e-03e038415f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'logoutDropdownLink' and (text() = 'Se déconnecter' or . = 'Se déconnecter')]</value>
      <webElementGuid>603314cf-51ea-4508-91ac-06ff837cc603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
