<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Afficher toutes les notifications_userS_5bf2a2</name>
   <tag></tag>
   <elementGuidId>26f660a4-f5d9-45d9-9ab1-28958050be88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.userShot.userImageCenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='userMenuDropdownLink']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbf0f04e-b4c9-4912-8f74-60150293b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automationid</name>
      <type>Main</type>
      <value>user-avatar</value>
      <webElementGuid>b869c30f-7b73-4af6-8dad-4156dbe1f880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userShot userImageCenter</value>
      <webElementGuid>bf56a18d-bab2-4621-8129-e0dd685ba043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userMenuDropdownLink&quot;)/div[@class=&quot;userShot userImageCenter&quot;]</value>
      <webElementGuid>fa6652a6-a991-4784-b6b0-0c194fd534c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='userMenuDropdownLink']/div</value>
      <webElementGuid>f5a8b766-333e-4cc6-a543-46840574f07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>cdc293ba-ca2b-4858-a692-8de07f611b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
