<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Datenbank_homeTile-1030-btnIconEl</name>
   <tag></tag>
   <elementGuidId>f7320096-4b7b-43bb-9a86-5cf20fe914d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='homeTile-1030-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homeTile-1030-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5012385d-5c67-43f8-a800-14051bd21464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homeTile-1030-btnIconEl</value>
      <webElementGuid>bc0bb8d5-d6ee-4f5f-b7a8-fb74ae6d6d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x4-btn-icon mki3-data-cloud-svg</value>
      <webElementGuid>13e0a237-3809-4dac-9957-efd2191adfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homeTile-1030-btnIconEl&quot;)</value>
      <webElementGuid>de4ba6cb-0f5e-43e6-ad4e-fec6a683d8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mein Marketo/iframe_henkeladhesivessandbox_mlm</value>
      <webElementGuid>bdbc209f-2a62-4549-8fe4-a5a4c8d187d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='homeTile-1030-btnIconEl']</value>
      <webElementGuid>fb5e1d24-2f6f-42dc-a170-29951d7abfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='homeTile-1030-btnEl']/span[2]</value>
      <webElementGuid>db583972-16cd-435d-a4e9-f9f4ff44e18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/em/a/span[2]</value>
      <webElementGuid>10e58d35-036e-4bad-914d-46d33580c176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'homeTile-1030-btnIconEl']</value>
      <webElementGuid>91ca9779-8a22-4d07-8b0f-7df6786cf692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
