<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONNEXION</name>
   <tag></tag>
   <elementGuidId>22d7d765-fb5e-493c-aafe-c50badd4212d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-f4f1d682f9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-f4f1d682f9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d9a8717-081f-4c5a-9d39-8143206523d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-f4f1d682f9</value>
      <webElementGuid>5bc1bce3-ab37-414f-8284-317e95701d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>calltoaction1661250876704</value>
      <webElementGuid>1ac245b7-d8bb-4436-959c-6b573742be31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta </value>
      <webElementGuid>1195e7d5-0a0f-404a-af9f-36181413e0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr/fr/bienvenue/login.html</value>
      <webElementGuid>1cf7a417-64a3-42d5-a1ac-45b670d99b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;&quot;}</value>
      <webElementGuid>68e09f64-c2f2-4575-bf0a-a43925e9ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>1abf6fd3-a24b-4075-9371-1b0b8b34478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          CONNEXION
      </value>
      <webElementGuid>ee3bfeb3-f5dc-432d-b718-b8acef876e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-f4f1d682f9&quot;)</value>
      <webElementGuid>90d91abe-5ea5-4253-91ee-9167fcc6c0fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-f4f1d682f9']</value>
      <webElementGuid>047fd62d-088e-4476-acf2-27716fabb5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-f4f1d682f9']/div/a</value>
      <webElementGuid>89bbe90c-e23d-4490-9d26-91bd8416116a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[1]/following::a[3]</value>
      <webElementGuid>7ef514af-550e-47d7-b552-dd3b939d0068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('S', &quot;'&quot;, 'ENREGISTRER')])[1]/preceding::a[1]</value>
      <webElementGuid>c8dcf004-4cda-4001-9922-59cf502edbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fr/fr/bienvenue/login.html')]</value>
      <webElementGuid>0e639383-ea4d-40aa-b6b3-882bea4afc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>06e4a0c9-a35e-4bf2-9797-791c43794293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-f4f1d682f9' and @href = '/fr/fr/bienvenue/login.html' and (text() = '
          
          CONNEXION
      ' or . = '
          
          CONNEXION
      ')]</value>
      <webElementGuid>edb238a0-5d3b-453b-8422-bbd62ef5a729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
