<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil</name>
   <tag></tag>
   <elementGuidId>ce9801ae-632d-4565-b4c9-4d7ac0dc4d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title__link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title-ff8319a067']/h5/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1775f06b-eec2-44b8-ae2b-e35fa6896bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title__link</value>
      <webElementGuid>5eab16ad-7341-424e-8bff-2343df423669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr/fr/user/profile.html</value>
      <webElementGuid>7cc0863b-4f54-4d42-8427-0376190128fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profil</value>
      <webElementGuid>1623c3b8-b212-4944-bb34-b29fb19144bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-ff8319a067&quot;)/h5[@class=&quot;heading5 hide-if-empty-placeholder apply-margins apply-font-style title__heading&quot;]/a[@class=&quot;title__link&quot;]</value>
      <webElementGuid>a8f3ccd5-a9cc-4ae1-aea2-aae3e407994d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-ff8319a067']/h5/a</value>
      <webElementGuid>0d795e7f-5513-440d-8bc6-2af97e05f937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Profil')]</value>
      <webElementGuid>2c0072cb-7f38-42f5-acda-6710d9dce279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonjour, Bobby!'])[1]/following::a[1]</value>
      <webElementGuid>0252365a-c741-4b50-81c5-ae498b024d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS'])[1]/following::a[1]</value>
      <webElementGuid>c4bc51fc-6e4e-4a91-90eb-07047eb724b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>e93934ca-de48-4d63-855c-9e7c310ce9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questionnaire'])[1]/preceding::a[2]</value>
      <webElementGuid>c6821dd8-e772-4493-a9ec-60b48e5c2386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profil']/parent::*</value>
      <webElementGuid>a47c6211-1c56-43b9-90d9-25ec05a01d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fr/fr/user/profile.html')]</value>
      <webElementGuid>9d4395d3-708c-431b-abdd-bc8269e87a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/a</value>
      <webElementGuid>f407c5e4-c380-47c3-bdaa-d6c3e3369dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fr/fr/user/profile.html' and (text() = 'Profil' or . = 'Profil')]</value>
      <webElementGuid>ec69dab8-16dc-40ef-ae3b-fe342411212e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
