<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__login__button login__button--login cta</name>
   <tag></tag>
   <elementGuidId>19137f06-d3fd-4ebf-9b03-fdb1ba2ae7d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.login__button.login__button--login.cta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7af19190-bfc4-4c60-8dd6-d7f8e70e91cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__button login__button--login cta</value>
      <webElementGuid>4d820235-1e9f-49f6-8e17-5939872e08cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login--loggedOut login1667733523206&quot;]/button[@class=&quot;login__button login__button--login cta&quot;]</value>
      <webElementGuid>5f93e90b-4138-430e-971d-bb1b8d5baac3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button</value>
      <webElementGuid>bd91c54a-1261-46ff-9780-bc174e8a42ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[1]/following::button[2]</value>
      <webElementGuid>25765724-f039-4c8d-9445-f89c565ff6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNEXION'])[1]/preceding::button[2]</value>
      <webElementGuid>e07bffcb-5b64-4b4e-96f1-67525e0bf759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('S', &quot;'&quot;, 'ENREGISTRER')])[1]/preceding::button[2]</value>
      <webElementGuid>776f45f5-0092-4543-8322-bebb76fb539a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>256b97eb-1145-4438-b5c7-a52634f24a6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
