<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__login__button login__button--login cta</name>
   <tag></tag>
   <elementGuidId>19137f06-d3fd-4ebf-9b03-fdb1ba2ae7d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login__button.login__button--login.cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb85c6f1-b3fa-4adc-827d-82d3d7ef8f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__button login__button--login cta</value>
      <webElementGuid>08ec07f3-526f-4632-a341-64e284662f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login--loggedOut login1667733523206&quot;]/button[@class=&quot;login__button login__button--login cta&quot;]</value>
      <webElementGuid>de684017-6605-4b50-950f-b5a9733430b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button</value>
      <webElementGuid>b846fb2f-e337-4dea-9a31-46cf97132550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATALOGUE'])[1]/following::button[2]</value>
      <webElementGuid>9f74b26b-e463-484a-ac6a-a35a579aff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNEXION'])[1]/preceding::button[2]</value>
      <webElementGuid>fe678210-3b39-40d8-ba58-92fd4f406393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('S', &quot;'&quot;, 'ENREGISTRER')])[1]/preceding::button[2]</value>
      <webElementGuid>c47f83a5-1dee-4172-b448-49d3925ba0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>9981b81a-149c-474a-a19f-a231bccb42b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
