<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SENREGISTRER</name>
   <tag></tag>
   <elementGuidId>d650fbbf-0f2a-4e10-9df8-8732d38ae300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-78b26aa002']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-78b26aa002 > span.calltoaction__text.calltoaction__text--initial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3fe7561-b3ce-4dcb-881b-b3d0a7537d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__text calltoaction__text--initial</value>
      <webElementGuid>105b326b-2b5c-4dc4-bb1d-85101dbcafb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S'ENREGISTRER</value>
      <webElementGuid>f994788a-d9ab-4917-a3f2-67519f5d2cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-78b26aa002&quot;)/span[@class=&quot;calltoaction__text calltoaction__text--initial&quot;]</value>
      <webElementGuid>5012343c-a3ed-4deb-bca7-80a9eca40c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-78b26aa002']/span</value>
      <webElementGuid>21dfde5d-95f1-49e9-b9df-bf231d8f0e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONNEXION'])[1]/following::span[1]</value>
      <webElementGuid>263475d5-b557-43e0-aee0-a223d7a91b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHWARZKOPF PROFESSIONAL'])[1]/preceding::span[1]</value>
      <webElementGuid>085e98fc-a6b9-40cf-bc2b-77c210be5d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP'])[1]/preceding::span[2]</value>
      <webElementGuid>137bdcf8-b58f-403c-be2f-22f7bd6a2ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-calltoaction[2]/div/div/a/span</value>
      <webElementGuid>87484f19-df07-4ad4-a74f-55128e1825b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;S&quot; , &quot;'&quot; , &quot;ENREGISTRER&quot;) or . = concat(&quot;S&quot; , &quot;'&quot; , &quot;ENREGISTRER&quot;))]</value>
      <webElementGuid>25d8fb75-ac49-430c-9f47-ffadd20e3e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
