<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Henkel-adhesives.com_image__img</name>
   <tag></tag>
   <elementGuidId>a42a2c16-95d1-410f-9a5c-06d6e185d71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ratiologo-82348fe50d']/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>345c4107-05db-4cd6-929d-76dea3c3fef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>logo-82348fe50d</value>
      <webElementGuid>af3a7e85-4f4b-4506-ab02-46cc5a92e081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Henkel Logo</value>
      <webElementGuid>8a24d297-7da9-413f-887d-f0b2c72a009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image__img</value>
      <webElementGuid>72b5d2f9-0ae9-4bbf-ab98-8362d4eab905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>5a707d58-368a-4884-9ee4-b81f9d106e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>186</value>
      <webElementGuid>025f4ca7-158f-4b6d-b756-5bd5e69a5e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==</value>
      <webElementGuid>d9a4a192-7e92-45bc-a21a-1872352914d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>65vw</value>
      <webElementGuid>714df95e-3ded-4cf8-9925-0dca36172704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=3360&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 3360w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=2560&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 2560w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=1600&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 1600w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=1024&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 1024w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=720&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 720w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=360&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 360w,https://dm.henkel-dam.com/is/image/henkel/henkel-logo-png?wid=180&amp;fmt=webp-alpha&amp;qlt=90&amp;fit=hfit,1 180w</value>
      <webElementGuid>7a5775f5-a864-4cb0-a2b9-5a90950aa463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experiencefragment-4825bb645c&quot;)/div[@class=&quot;xfpage page basicpage&quot;]/div[@class=&quot;xf-content-height&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/heliux-header[@class=&quot;header primary aem-GridColumn aem-GridColumn--default--12&quot;]/header[@class=&quot;header__base  container-max header1648763086882&quot;]/div[@class=&quot;header__container&quot;]/div[@class=&quot;header__logo&quot;]/heliux-logo[@class=&quot;logo alignment-horizontal-start margin-block-start-default margin-block-end-default&quot;]/div[@id=&quot;logo-82348fe50d&quot;]/a[@class=&quot;image__link&quot;]/div[@id=&quot;ratiologo-82348fe50d&quot;]/picture[@class=&quot;image__imgPreview&quot;]/img[@class=&quot;image__img&quot;]</value>
      <webElementGuid>d0d7c37f-66af-4b78-a96c-f085cb197682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ratiologo-82348fe50d']/picture/img</value>
      <webElementGuid>269cd676-9f06-4e02-8974-3b3dc77b0b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Henkel Logo']</value>
      <webElementGuid>c7716693-cad0-46b7-a1d0-a0be94623ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d1244eec-091a-4a24-ad5b-b46f55572c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Henkel Logo' and @src = 'data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==']</value>
      <webElementGuid>b7238404-adb2-455c-9de2-6ddfc9198c91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
