<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up now</name>
   <tag></tag>
   <elementGuidId>a836659e-492c-4bf8-a5ae-346c83023604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='createAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b7a9943-db7f-41df-be8e-b203e4abc887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createAccount</value>
      <webElementGuid>76988f91-13a5-4367-91f5-6bef64197afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/henkelgroupciamtest.onmicrosoft.com/B2C_1A_SignInUp_ProgramNow/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=TXY0RkdDN1B3ZnBndUNWRGFnQU9qUjVZRTZFSHlJZGlDRGFzc3RRSGtkSnBWb05BS1QyMFZoQ0t6VUEyZmdnVlMxcHd0R3pXcEgzcGJONXNqRFlONVE9PTsyMDIzLTAxLTExVDE0OjUzOjQ0LjkwODYzMjlaO3Iya1B1VHQybjFjaUlwQlVpdE54VVE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==&amp;tx=StateProperties=eyJUSUQiOiI2YWRkMDMzZC05N2ZiLTRiMjQtYWVjZS02ZDlkNTBkODg3ODIifQ&amp;p=B2C_1A_SignInUp_ProgramNow</value>
      <webElementGuid>75315da8-f24d-4b82-862b-c2fec49f05cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up now</value>
      <webElementGuid>9201fb42-498c-47c8-a98e-f9ad3e1572cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createAccount&quot;)</value>
      <webElementGuid>dca6b46f-8c65-4a8c-8666-594c25d4a6e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='createAccount']</value>
      <webElementGuid>c09866ee-7e28-41b4-9546-9b19308e9658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[5]/p/a</value>
      <webElementGuid>23e2821a-ce4e-4ebf-a71c-a35e79256c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up now')]</value>
      <webElementGuid>3577ce1d-f675-4751-8209-7bd16dcdc313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[2]/following::a[1]</value>
      <webElementGuid>44c8bbb7-7d3c-4a8c-bf1a-1abd60597aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::a[1]</value>
      <webElementGuid>e2f26586-7d8f-4cdb-a16c-08ec9722028a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We make it happen'])[1]/preceding::a[1]</value>
      <webElementGuid>a1adc5a2-1c4c-42fe-a807-158d872be280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up now']/parent::*</value>
      <webElementGuid>f81d631a-907e-4424-9b92-eee9f9f89a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/henkelgroupciamtest.onmicrosoft.com/B2C_1A_SignInUp_ProgramNow/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=TXY0RkdDN1B3ZnBndUNWRGFnQU9qUjVZRTZFSHlJZGlDRGFzc3RRSGtkSnBWb05BS1QyMFZoQ0t6VUEyZmdnVlMxcHd0R3pXcEgzcGJONXNqRFlONVE9PTsyMDIzLTAxLTExVDE0OjUzOjQ0LjkwODYzMjlaO3Iya1B1VHQybjFjaUlwQlVpdE54VVE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==&amp;tx=StateProperties=eyJUSUQiOiI2YWRkMDMzZC05N2ZiLTRiMjQtYWVjZS02ZDlkNTBkODg3ODIifQ&amp;p=B2C_1A_SignInUp_ProgramNow')]</value>
      <webElementGuid>9d0e7441-9898-406c-b625-049f6d88726b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e800f846-f11f-4833-8657-fb236590ac15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'createAccount' and @href = '/henkelgroupciamtest.onmicrosoft.com/B2C_1A_SignInUp_ProgramNow/api/CombinedSigninAndSignup/unified?local=signup&amp;csrf_token=TXY0RkdDN1B3ZnBndUNWRGFnQU9qUjVZRTZFSHlJZGlDRGFzc3RRSGtkSnBWb05BS1QyMFZoQ0t6VUEyZmdnVlMxcHd0R3pXcEgzcGJONXNqRFlONVE9PTsyMDIzLTAxLTExVDE0OjUzOjQ0LjkwODYzMjlaO3Iya1B1VHQybjFjaUlwQlVpdE54VVE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==&amp;tx=StateProperties=eyJUSUQiOiI2YWRkMDMzZC05N2ZiLTRiMjQtYWVjZS02ZDlkNTBkODg3ODIifQ&amp;p=B2C_1A_SignInUp_ProgramNow' and (text() = 'Sign up now' or . = 'Sign up now')]</value>
      <webElementGuid>13760b76-1bb5-4935-ab90-04060fc2cb8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
