<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_Email Address</name>
   <tag></tag>
   <elementGuidId>d119a29c-027b-46c4-89ba-f529fa52838a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signInName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6a133b6-1257-4335-84a2-f6b06f3cc85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa3cbb6b-2bc4-403d-8d86-0150856a58a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInName</value>
      <webElementGuid>3aa135df-9267-4f4a-8061-bd44b54d3cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>4b3ef266-2c03-4fb1-9133-e5e1fa1787b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please enter a valid Email Address</value>
      <webElementGuid>ead58097-c6b8-4e23-9107-47b3ff2792cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>c053579d-8a7f-45d2-96bb-7c68e7234d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>2597f008-1cac-455e-a222-d279a0bf6ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInName&quot;)</value>
      <webElementGuid>e5588e9f-8ac7-48f7-976a-eefe5b2abfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInName']</value>
      <webElementGuid>c84dee7c-3826-4eee-a9e1-cf3808589c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div/input</value>
      <webElementGuid>77ffa9cb-408c-46d6-83f3-c702716b1af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>72be7af6-bd18-4a12-b324-101b6e3d1ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'signInName' and @name = 'Email Address' and @title = 'Please enter a valid Email Address' and @placeholder = 'Email Address']</value>
      <webElementGuid>5bb2d755-af6f-4780-a2a5-41478883d1ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
