<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gLFyf,.YacQvheight34pxfont-size16pxflex_8b6c18</name>
   <tag></tag>
   <elementGuidId>b2ad0cb4-03eb-4182-8610-e036097cbf04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a4bIc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7ac8078-4c96-448a-8858-8cd4afbf872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>vZr2rb</value>
      <webElementGuid>1d4ffba8-8b1b-4859-96d1-91f2b546fac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a4bIc</value>
      <webElementGuid>5f5b7ad9-7bac-4092-8347-bf17d50d1821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>gLFyf</value>
      <webElementGuid>7a8b50e2-2b97-4eac-ac5e-51ac7f3d8820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>h5M12e;input:d3sQLd;blur:jI3wzf</value>
      <webElementGuid>2f4cbe53-c589-4cac-831c-7a7b6ef91547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.gLFyf,.YacQv{height:34px;font-size:16px;flex:100%;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;-webkit-tap-highlight-color:transparent;margin-top:-37px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;white-space:pre}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}</value>
      <webElementGuid>80ae96cc-6021-4072-849b-8a1e0c652b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]/div[@class=&quot;a4bIc&quot;]</value>
      <webElementGuid>7380a59c-a790-4451-954e-b0de42bb626b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[16]</value>
      <webElementGuid>06045203-b7ee-4e5e-b0fe-8721a3e42f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::div[21]</value>
      <webElementGuid>07511e7f-9809-479d-bbe1-cfba4d729d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[18]</value>
      <webElementGuid>4c3443c3-36e3-4741-9c0c-7fbd9a055a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::div[22]</value>
      <webElementGuid>168b80fe-3fe2-4783-bab9-83bb7974bced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]</value>
      <webElementGuid>10cd4d81-8eb5-43c6-954a-5a3695a3a4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.gLFyf,.YacQv{height:34px;font-size:16px;flex:100%;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;-webkit-tap-highlight-color:transparent;margin-top:-37px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;white-space:pre}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}' or . = '.gLFyf,.YacQv{height:34px;font-size:16px;flex:100%;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;-webkit-tap-highlight-color:transparent;margin-top:-37px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;white-space:pre}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}')]</value>
      <webElementGuid>5e753762-1a21-4596-98c1-6422f6701d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
