<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_email</name>
   <tag></tag>
   <elementGuidId>72e9bc87-28ad-44cc-92ba-6789bbd7fcd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-textbox-115860621083771000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-textbox-115860621083771000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec2cce57-d0bc-446b-a87f-52786089861e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bb0d9886-2adb-43b8-b132-ea0bc9dfadde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-text</value>
      <webElementGuid>7f1c496e-f6e8-4a3b-87ea-93fa03f7413c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>546724e5-f057-447f-8712-38f702cd1263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2c9f34bc-29f9-4ce3-82df-d38182eff1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_103215656919167600_PLACEHOLDER']</value>
      <webElementGuid>bbd8c6c5-fa2b-40ab-abd6-c08ff623621f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:aria-label</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_103215656919167600_PLACEHOLDER']</value>
      <webElementGuid>49af3268-aefa-461e-9ef0-c54a4aa6a1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-textbox-115860621083771000</value>
      <webElementGuid>d44e30d4-7603-44ba-a563-efdf84fa0532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48922a4a-6a9d-4c1d-8ed2-98e7390b510f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>abd3aeb6-00c1-4257-8c31-bcf0cefaf3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f99b98f9-b086-42c6-8dbc-d57ab034e0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-textbox-115860621083771000</value>
      <webElementGuid>e0f40589-31d6-457f-b749-72028443966d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9579f936-c104-4506-97c4-8b5a066961e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>6fcc43f4-c5ce-4812-855b-239b09c0c067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address *</value>
      <webElementGuid>0ac69c19-af43-42bf-a004-e54a6dbbc0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>fb18d0e2-719e-44f7-a475-5b0d3f3dc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-textbox-115860621083771000&quot;)</value>
      <webElementGuid>32b7a78d-9d81-453b-830d-56f36ea20fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-textbox-115860621083771000']</value>
      <webElementGuid>79c49ca4-6209-4680-8152-3d2936adddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[4]/input</value>
      <webElementGuid>42904eef-346d-41a7-9084-afd4e9b51131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[4]/input</value>
      <webElementGuid>b37165c8-e2cd-4d85-b6d6-e6b6156b2f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'gigya-textbox-115860621083771000' and @placeholder = 'Email address *']</value>
      <webElementGuid>e2769d65-a3d1-4cc4-91b0-3a7703815743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
