<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_preferences.terms.HenkelLifeTimeToS.isConsentGranted</name>
   <tag></tag>
   <elementGuidId>ca3767c9-c81f-494f-9ba0-eabb573d524e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-checkbox-72004138349937020</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-checkbox-72004138349937020']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0590ba90-2e73-41f6-9309-6fb99494db62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5f50f420-89d5-45dd-91cb-09d84cf13898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-checkbox fd-checkbox</value>
      <webElementGuid>929b9290-2ae0-42a6-b719-abbbcf0f2df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelLifeTimeToS.isConsentGranted</value>
      <webElementGuid>aa1c0632-8b7c-4e0e-a65a-881955144d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>bfb5a055-2c92-4c12-a205-39565ae08647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-checkbox-72004138349937020</value>
      <webElementGuid>2c702c67-cf30-47d7-a092-8ce9e95d6643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bed6f7b1-7ecc-49f7-835a-3460ca4ccc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>6933ea77-b27d-4ef6-bc93-cb63d111f601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>preferences.terms.HenkelLifeTimeToS.isConsentGranted</value>
      <webElementGuid>04aa0303-12a5-40d4-81bc-22cb1aaba131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d4221e8-9299-45aa-9602-2a5593b5ab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-checkbox-72004138349937020</value>
      <webElementGuid>35dc3760-68e8-47b0-98dd-91072d3bba6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>991ab85c-90a8-4dab-abbf-b0258b4c0138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-checkbox-72004138349937020&quot;)</value>
      <webElementGuid>9dc01787-c6ed-4091-aed1-d699fee547b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-checkbox-72004138349937020']</value>
      <webElementGuid>befe9ce2-c7c9-44fa-8cf1-ce851b553a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/input</value>
      <webElementGuid>7bd19ee2-0741-4e22-97a6-902a51779638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[8]/input</value>
      <webElementGuid>7820e8e6-f663-4971-add6-5549bacc0901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'preferences.terms.HenkelLifeTimeToS.isConsentGranted' and @checked = 'checked' and @id = 'gigya-checkbox-72004138349937020']</value>
      <webElementGuid>01da5313-097e-4caa-8b84-e5dcda9e962c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
