<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_password</name>
   <tag></tag>
   <elementGuidId>00dad00b-58ae-445d-95ae-ed2fe55628ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-password-98020708136770500</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-password-98020708136770500']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2006deb7-29c7-40b2-b285-9185cf1b7232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f93f4576-0710-4c5a-8cda-57774f92ed77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-password</value>
      <webElementGuid>7bd700b8-ebd6-4c23-9688-31cfb57d6f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-conditional:show-password-strength</name>
      <type>Main</type>
      <value>screenset.width &lt; 900?up</value>
      <webElementGuid>5477820e-b507-410c-83ba-32000c398f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2add9ac3-16fe-4439-bb2c-dee33c18c7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>7aa4b7c9-9b85-46c5-90d5-1b77f497bc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_148905838322575840_PLACEHOLDER']</value>
      <webElementGuid>c9f2732d-a20e-41d1-a8bd-c208071dff42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:aria-label</name>
      <type>Main</type>
      <value>screenset.translations['PASSWORD_148905838322575840_PLACEHOLDER']</value>
      <webElementGuid>f969f76d-0b2d-4baa-ac88-40484076728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-password-98020708136770500</value>
      <webElementGuid>96722f3c-9ce9-44d5-a575-bbeb4c0a0ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ddada90-93be-4a7d-b623-9042e5260dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>8929f98f-a40b-4797-af50-d5ce7e01b870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-default-show-password-strength</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>df9c3125-badc-4034-99ad-56665950b0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>90e7c95d-6457-4c21-97f8-a321915d6230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-password-98020708136770500</value>
      <webElementGuid>3f766b69-1663-49ae-96af-6b6085969f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f3b60cf-2366-48db-abd3-4404c84aba2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>db3d3c92-9da5-456c-bb1b-1d55d6f825c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password *</value>
      <webElementGuid>4a559e09-c82e-4f23-bb45-0371fde22adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e28d10b1-106f-47a6-adf3-e9659401d331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-password-98020708136770500&quot;)</value>
      <webElementGuid>94d63cd0-1bfd-4bef-aa36-62c321d388d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-password-98020708136770500']</value>
      <webElementGuid>6b0bbddf-19e2-4471-b26f-6ecba93b5933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[5]/input</value>
      <webElementGuid>4b876587-673d-4c2f-b99e-33c2d63812b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[5]/input</value>
      <webElementGuid>e7603e61-42e8-4ffc-a7dc-60c26ab8d30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'gigya-password-98020708136770500' and @placeholder = 'Password *']</value>
      <webElementGuid>9af840bb-a162-4887-8756-ead05b9677c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
