<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice</name>
   <tag></tag>
   <elementGuidId>808e2852-a73e-493c-ad41-fec582beaf12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4eac68a-2635-4500-aac7-47cf7ecfef1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label-text gigya-checkbox-text</value>
      <webElementGuid>66a1f687-f7bd-4776-8a57-0f4801a5f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>CHECKBOX_72004138349937020_LABEL</value>
      <webElementGuid>ebbf6abf-42c7-40e5-823b-ebcd11a92568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_47_1676972646878</value>
      <webElementGuid>2fd89037-07a3-4e11-9136-3e2551a1a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4bb40b4-43d8-4b89-9d80-09be20905f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance,template</value>
      <webElementGuid>4cd4f4e9-baa4-4545-9661-6df31a6a723b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.</value>
      <webElementGuid>0ba4d623-8ee2-4913-846c-e3ad2cc61842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-lite-account-progression-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-checkbox gigya-terms-valid&quot;]/label[@class=&quot;gigya-label&quot;]/span[@class=&quot;gigya-label-text gigya-checkbox-text&quot;]</value>
      <webElementGuid>a1af4586-f40d-4db6-8971-2ef3d21cf263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-lite-account-progression-form']/div[2]/div[8]/label/span</value>
      <webElementGuid>d9ad2c96-38f1-4b89-90a2-94628253eb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::span[7]</value>
      <webElementGuid>2b753bcc-ba81-4081-bd60-7cc579fdcb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='®'])[3]/following::span[10]</value>
      <webElementGuid>168e4c05-3e1e-430e-be12-0120b9aa76ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes, I accept the']/parent::*</value>
      <webElementGuid>988c0c56-cd7b-4d16-bd83-1051db87ad74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[8]/label/span</value>
      <webElementGuid>208b648d-7919-4af2-b081-6f331d1a842f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.' or . = 'Yes, I accept the Terms of Use. For information on purposes for which we use your information, see our Privacy Policy and CA Privacy Notice.')]</value>
      <webElementGuid>00cf8a60-37eb-4600-b7bf-5c4f20135f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
