<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COMPARE_teaserlist__item-link</name>
   <tag></tag>
   <elementGuidId>a7ac749f-bd5e-4809-b50a-0eae006f91db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='teaserlist-450e73662a']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b4bc557-67e4-4952-a351-c83d3ab91d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>teaserlist__item-link</value>
      <webElementGuid>2cfb0325-1ebf-4888-bada-b6bd846fa650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LOCTITE 510</value>
      <webElementGuid>54a7d010-830f-46e2-ba29-9577bcd452b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html</value>
      <webElementGuid>56ca5ba1-ecad-4de6-bc8c-a331360c5058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>8c2bbe26-9b03-420b-bfa7-60eda83c2913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teaserlist-450e73662a&quot;)/ul[@class=&quot;teaserlist__items atomic--target
                teaserlist__items--loadMore&quot;]/li[@class=&quot;teaserlist__item&quot;]/a[@class=&quot;teaserlist__item-link&quot;]</value>
      <webElementGuid>7dcab366-51ca-49b6-b659-9fb1589370ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='teaserlist-450e73662a']/ul/li[2]/a</value>
      <webElementGuid>f3893bfc-e258-4ab5-ae7c-b067e1aed70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPARE'])[1]/following::a[1]</value>
      <webElementGuid>01e5c402-12ea-41a5-a865-e6e124fb8cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW'])[1]/following::a[1]</value>
      <webElementGuid>0b43c600-166d-4335-9bd8-0662c147c459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW'])[2]/preceding::a[1]</value>
      <webElementGuid>56995ae7-5573-4e1b-a90e-37470b99811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html')]</value>
      <webElementGuid>d5da8c1d-6b85-4684-88c3-c203039a737e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-section[2]/div[3]/heliux-teaserlist-v2/div/ul/li[2]/a</value>
      <webElementGuid>5a89a392-2913-4879-a314-5e98e5715464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'LOCTITE 510' and @href = 'https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html']</value>
      <webElementGuid>4b9f03be-8fdb-43a8-ae33-cdabac5fbdb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
