<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW</name>
   <tag></tag>
   <elementGuidId>383cef56-c6c4-40b8-998b-490924a8edd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-ce44ad31d2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-ce44ad31d2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54f4ecaf-ca62-42f2-8cae-67aff71f9aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-ce44ad31d2</value>
      <webElementGuid>42fb98ef-5481-4bd7-a1cd-c875aaa52ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>calltoaction1653653245114</value>
      <webElementGuid>d0069ef0-ef1c-4ed7-a415-c933e2e8436d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta </value>
      <webElementGuid>27d2a6d1-1828-4cf2-a80b-145f3d5b9dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html</value>
      <webElementGuid>608de96a-d3c9-46ac-9223-7ad9f9151569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;&quot;}</value>
      <webElementGuid>98e95bbb-5120-498c-b285-fd96382b7e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>760e7d05-8017-4510-ac53-cbda6ed13517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>44230e3b-5f6b-4bbe-8f07-8e4b9cb7d52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          VIEW
      </value>
      <webElementGuid>502f2735-3df3-4b52-8129-fc1ccde0a339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-ce44ad31d2&quot;)</value>
      <webElementGuid>1f3ad81b-f6b1-4b24-b90e-60357f869f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-ce44ad31d2']</value>
      <webElementGuid>c21bba0a-8dbc-4a4f-bd7d-9419cfbfb413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-ce44ad31d2']/div/a</value>
      <webElementGuid>bae9f31b-6efa-4afc-9e4b-2c77bec6910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPARE'])[1]/following::a[2]</value>
      <webElementGuid>2faffcd2-40ee-432f-8434-085a55c39b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPARE'])[2]/preceding::a[1]</value>
      <webElementGuid>94984acb-c5bb-4362-ae2d-815b8278c542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html')])[2]</value>
      <webElementGuid>b0d0759d-b800-4979-a774-d52acf449685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/heliux-section/div[3]/heliux-calltoaction/div/div/a</value>
      <webElementGuid>edd0af4a-c98f-451e-8a69-755309f8bc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-ce44ad31d2' and @href = '/us/en/products/industrial-sealants/gasketing-sealants/loctite-510.html' and (text() = '
          
          VIEW
      ' or . = '
          
          VIEW
      ')]</value>
      <webElementGuid>8663b3f3-8e38-4a88-9d30-eccb694606ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
