<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Hi Bobby,</name>
   <tag></tag>
   <elementGuidId>5e249e5f-de0d-4926-a003-09f98795f75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-account-profile-form > div.gigya-layout-row.subscribe-wrapper > label.gigya-composite-control.gigya-composite-control-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-account-profile-form']/div[8]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d7ccec00-439f-4640-8905-82d1aa31df50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-composite-control gigya-composite-control-label</value>
      <webElementGuid>15352aeb-b741-4a27-a4cc-2b7f62529d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ef7dce5-80b7-4a2a-8ba5-d30423564c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>LABEL_38300411233912800_LABEL</value>
      <webElementGuid>8c7d1379-e135-4683-8489-b7887d68bd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_293_1676528174253</value>
      <webElementGuid>6e00ed7a-1a40-44e6-ae34-866e51e14350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50488fa1-cf3e-4ab3-9bc4-046431853da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>template,instance,instance</value>
      <webElementGuid>eff608dd-bc23-4b3f-b8d0-d2edcd02defc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi Bobby,</value>
      <webElementGuid>eb0e3fb5-09ac-4581-874f-90b6afc5cceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-account-profile-form&quot;)/div[@class=&quot;gigya-layout-row subscribe-wrapper&quot;]/label[@class=&quot;gigya-composite-control gigya-composite-control-label&quot;]</value>
      <webElementGuid>74135bf1-5548-4e8e-8614-a2f4461e43a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-account-profile-form']/div[8]/label</value>
      <webElementGuid>69e2f935-1ad3-4d14-b8eb-b35e6a425f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Photo'])[1]/following::label[1]</value>
      <webElementGuid>50fa6986-2ce8-4bb4-a2ce-a53d98313c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size:'])[1]/following::label[1]</value>
      <webElementGuid>79a584b2-4acf-4b18-9c09-a0d8cb12570d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Benefits'])[1]/preceding::label[2]</value>
      <webElementGuid>6bedafb8-f146-4d42-82c6-97e8c3bc0c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW: Our Laundry Symbol Scanner is now available!'])[1]/preceding::label[2]</value>
      <webElementGuid>9735b347-4535-44ba-a802-a6df7e3d65de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hi Bobby,']/parent::*</value>
      <webElementGuid>a2ea3a65-1475-48fb-bb06-1e793b3b05e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[8]/label</value>
      <webElementGuid>0f07cecc-e624-453c-aff9-7fe30ea09402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Hi Bobby,' or . = 'Hi Bobby,')]</value>
      <webElementGuid>258d1c69-5576-4001-aaf2-4449ec19fd95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
