<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Personal</name>
   <tag></tag>
   <elementGuidId>8ca3bee9-0dc4-4c87-98f7-d60f9a90ae4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ext-gen173']/em/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43c3959b-0e6a-43e6-be4a-c4c9c7e0b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-strip-text </value>
      <webElementGuid>4feebdb8-3408-4a9d-b7d4-b51bee894927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal</value>
      <webElementGuid>e6c85ab7-35b7-4d16-b453-c4f315f5f2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen173&quot;)/em[@class=&quot;x-tab-left&quot;]/span[@class=&quot;x-tab-strip-inner&quot;]/span[@class=&quot;x-tab-strip-text&quot;]</value>
      <webElementGuid>8803ef4e-3a00-4b54-b96a-4333ef31ce7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Alle Personen  Smart Lists fr System  _a162ad/iframe_Training_mlm</value>
      <webElementGuid>c5ebbe4a-52d6-40f4-b274-3557716bc739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ext-gen173']/em/span/span</value>
      <webElementGuid>f0b19aba-b6b4-4d55-b38a-f4cd3f45bb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alle Personen'])[1]/following::span[2]</value>
      <webElementGuid>4fde0804-8c9d-473a-b8a3-5794fb3ed67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart List'])[1]/preceding::span[1]</value>
      <webElementGuid>6e63f543-82e6-4f20-be56-345b06f8f350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neu'])[1]/preceding::span[4]</value>
      <webElementGuid>3d2e5ed5-345e-4b9f-b319-997f3fca74c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personal']/parent::*</value>
      <webElementGuid>508dcaf0-c366-479b-a4ff-49a625c3f545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/em/span/span</value>
      <webElementGuid>ee77b1af-5e3a-4caf-b188-2e842e0b1d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Personal' or . = 'Personal')]</value>
      <webElementGuid>ea2dc911-17d9-46a9-93cd-3b44d99d5d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
