<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUAIMERIEZ-VOUS APPRENDRE</name>
   <tag></tag>
   <elementGuidId>4af64431-6c56-40d8-93cf-6c5e24afc859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calltoaction-fedd7b9e95</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='calltoaction-fedd7b9e95']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8172fd5-5494-4c57-8faf-75c95e49c5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calltoaction-fedd7b9e95</value>
      <webElementGuid>56c6619c-d2f3-4b5f-b7b4-9ce77f9fff16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>calltoaction1634543529524</value>
      <webElementGuid>5ea9a7b1-88e1-4bc2-a7c2-39fdae0d088d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta </value>
      <webElementGuid>8ab7f7fb-8a84-4a98-9049-47d7d0af3db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fr/fr/catalogue.html</value>
      <webElementGuid>3766e644-435e-42ff-9e0b-2cfa0fad7485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;&quot;}</value>
      <webElementGuid>5f14d383-3cde-4bd5-bfd7-0b3a786b8d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>711e4bf6-e300-4eb9-a1a1-4c154bf91162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>d81b80dc-4d85-4604-a932-a9442d5d5c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          QU'AIMERIEZ-VOUS APPRENDRE ?
      </value>
      <webElementGuid>a47e02c1-3a65-418b-b6c6-9e69b9422d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calltoaction-fedd7b9e95&quot;)</value>
      <webElementGuid>3894b1ab-b91b-4651-85ec-313192aa4a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calltoaction-fedd7b9e95']</value>
      <webElementGuid>dbe1cd84-e6b5-4c66-8c2a-fde13a751f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-fedd7b9e95']/div/a</value>
      <webElementGuid>d7efce09-a600-46c9-b4f5-47a269ab4fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BIENVENUE SUR LA NOUVELLE eACADEMY!'])[1]/following::a[1]</value>
      <webElementGuid>e8768e78-fb14-4056-aca0-7aa3900335af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASK EDUCATION'])[1]/following::a[1]</value>
      <webElementGuid>3035ad19-6e37-42b5-9ee4-5eb088021a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOI DE NEUF ?'])[1]/preceding::a[1]</value>
      <webElementGuid>1591d178-2efe-44ce-958a-d370828fbd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/fr/fr/catalogue.html')])[3]</value>
      <webElementGuid>eaa7aea7-1994-4a85-9315-2675490be511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>d398ef5b-0115-425a-80a4-23f1f0831995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calltoaction-fedd7b9e95' and @href = '/fr/fr/catalogue.html' and (text() = concat(&quot;
          
          QU&quot; , &quot;'&quot; , &quot;AIMERIEZ-VOUS APPRENDRE ?
      &quot;) or . = concat(&quot;
          
          QU&quot; , &quot;'&quot; , &quot;AIMERIEZ-VOUS APPRENDRE ?
      &quot;))]</value>
      <webElementGuid>3a046924-a2d4-44c1-af6e-67b7dda9769d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
