<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start</name>
   <tag></tag>
   <elementGuidId>7a03058c-2faf-4dbf-a11e-336667d08591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pf__cta.pf__nextStep</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61ba2f5a-b94a-4a9f-9b1c-0f969910caa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53642332-bc5c-4d42-81c3-4125727db1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf__cta pf__nextStep</value>
      <webElementGuid>3c86f7af-757a-469a-997d-fd3c001daae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>327bd62b-53ce-4a88-9e63-a77cef35fe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pf-root&quot;)/div[@class=&quot;pf__app&quot;]/div[@class=&quot;pf__wrapper&quot;]/div[@class=&quot;pf__formWrapper&quot;]/div[1]/div[@class=&quot;pf__welcomeScreen&quot;]/button[@class=&quot;pf__cta pf__nextStep&quot;]</value>
      <webElementGuid>abe561cd-6259-4258-bed6-a11695d6e35b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>ac184e27-d682-4189-802d-df6555c67308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pf-root']/div/div/div/div/div/button</value>
      <webElementGuid>9b4b67cb-4c34-44aa-ad2f-0e982d222543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interests, skills and knowledge'])[1]/following::button[1]</value>
      <webElementGuid>69391aec-6943-4de3-83fd-9758ce7f1bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTES POUR LES RÉSIDENTS DES ÉTATS-UNIS'])[1]/following::button[2]</value>
      <webElementGuid>ca3892cb-46c2-47d7-af7e-e9cac5fddb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can quit anytime and Continue later'])[1]/preceding::button[1]</value>
      <webElementGuid>975d44fc-9df2-40c2-9a6c-b0a119ba5143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start']/parent::*</value>
      <webElementGuid>f0324ae8-451f-4737-a0b2-f9c720247af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>85ed4116-22f0-46e3-aaee-091d6071df81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>5d1424f8-046a-4463-84df-386b9d78f921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
