<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__modal__overlay</name>
   <tag></tag>
   <elementGuidId>7738d23b-1c59-4263-a8d5-9d9912517358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-modalopener-4d4482fc4f']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal__overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13cb3df1-65b5-4267-91f7-45b7887a90b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal__overlay</value>
      <webElementGuid>d964673f-bf6b-44c1-8cd1-b78509e79750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-modalopener-4d4482fc4f&quot;)/div[@class=&quot;modal__overlay&quot;]</value>
      <webElementGuid>e6e39450-c934-4196-971a-37b06a2f0063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalopener-4d4482fc4f']/div</value>
      <webElementGuid>768c0327-16dd-482c-9485-9d90d546b833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>b90c2581-471e-49fd-8a4d-b21a13d94b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
