<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Interests, skills and knowledgeStartYou can quit anytime and Continue later</name>
   <tag></tag>
   <elementGuidId>50edbfdd-09d9-41bc-a4e1-7e55511b43b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>e</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pf__wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0b6d8d7-bbed-4e8d-9f78-cc3e53e99c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf__wrapper</value>
      <webElementGuid>6379a877-9dc7-4219-9afc-23d49b2a9ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interests, skills and knowledgeStartYou can quit anytime and Continue later</value>
      <webElementGuid>26b511e5-39e8-4247-a2e0-5d7671f97238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pf-root&quot;)/div[@class=&quot;pf__app&quot;]/div[@class=&quot;pf__wrapper&quot;]</value>
      <webElementGuid>fbe12f3a-31c7-4ff4-9ebc-5e4017aa7529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pf-root']/div/div</value>
      <webElementGuid>adcfccbe-7116-4a99-8fd7-c5402418285e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[23]</value>
      <webElementGuid>b9750af6-72ce-45c5-aacd-c61e53eb7d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[23]</value>
      <webElementGuid>0ff675fe-2bea-4f34-95eb-244df0aab99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>302e7a4f-8f02-4a8d-9a07-f777fd3d32c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later' or . = 'Interests, skills and knowledgeStartYou can quit anytime and Continue later')]</value>
      <webElementGuid>780fd94e-97ae-4ddf-91b2-7104c15764c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
