<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , pf-root, , ))_modal__overlay</name>
   <tag></tag>
   <elementGuidId>c970e494-0359-4061-a735-e48ab95a638d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-modalopener-4d4482fc4f']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal__overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85a5fee4-aeff-4a21-a521-141a9b0eeaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal__overlay</value>
      <webElementGuid>367cae14-087f-4bcf-8682-708d09581728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-modalopener-4d4482fc4f&quot;)/div[@class=&quot;modal__overlay&quot;]</value>
      <webElementGuid>8ca2a382-168c-44bc-af31-267e46034e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalopener-4d4482fc4f']/div</value>
      <webElementGuid>fad84ea1-4afc-4ad9-ab8d-389a5661937e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>4c9af017-9d88-486b-8868-58a7b457f28c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
