<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DCOUVREZ LE PORTEFEUILLE IGORA_image__img</name>
   <tag></tag>
   <elementGuidId>f2287b55-54fe-40fd-b077-f892759b8a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ratiobackground-9231597eeb']/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ratiobackground-9231597eeb > picture.image__imgPreview.image__imgPreview--lazy > img.image__img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f09e3cc-b13e-4b99-ad0a-d75139d1e16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>background-9231597eeb</value>
      <webElementGuid>7339ea00-e54c-40fe-a0b9-a2d2a89a2039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Model with scarab coloured hair</value>
      <webElementGuid>98220f19-2226-4cdc-a623-e856d28eb44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image__img</value>
      <webElementGuid>89d23e42-1427-4ff9-ac6d-f451c6ddcb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>9ef1b829-9421-4d06-9820-01dee4867078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>188</value>
      <webElementGuid>3f4082ff-bf83-497d-aaff-7e242b808127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==</value>
      <webElementGuid>31212f0b-b9d5-43b8-9ecc-47a2fd514b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>86998a92-b1d7-4ba2-8c27-4f4f870f2ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>7ce8ec8d-aaaf-4e46-aea5-00e7b1ad5d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=240&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 240w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=480&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 480w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=768&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 768w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=1024&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1024w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=1280&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1280w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=1440&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1440w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=1680&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1680w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-EL-1-2022?wid=2560&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 2560w</value>
      <webElementGuid>17e7dd2a-8611-4ba0-8f39-548b674974e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratiobackground-9231597eeb&quot;)/picture[@class=&quot;image__imgPreview image__imgPreview--lazy&quot;]/img[@class=&quot;image__img&quot;]</value>
      <webElementGuid>19654238-b330-42f1-8e83-4fa15b92ff31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ratiobackground-9231597eeb']/picture/img</value>
      <webElementGuid>3502c824-3582-47a3-9bc7-71127fbb78ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Model with scarab coloured hair']</value>
      <webElementGuid>74d30ed8-30a8-4b38-a697-467d689bbb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/picture/img</value>
      <webElementGuid>f3998d35-6488-4884-a21d-ddb0f3e0631a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Model with scarab coloured hair' and @src = 'data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==']</value>
      <webElementGuid>7428b27e-222a-478a-a6fe-2ce4cfe71dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
