<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DCOUVREZ LES NUANCES MODE IGORA_image__img</name>
   <tag></tag>
   <elementGuidId>722111bb-39d5-4a63-91a4-39af44ce3ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ratiobackground-885f840f84']/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ratiobackground-885f840f84 > picture.image__imgPreview.image__imgPreview--lazy > img.image__img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>59fe21c2-0d33-4c38-ba44-861dcbc02445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>background-885f840f84</value>
      <webElementGuid>11ee5268-3c21-4809-85bc-94ee7492ed52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Model with scarab coloured hair</value>
      <webElementGuid>649cf006-bd7c-4f86-8424-078daa521c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image__img</value>
      <webElementGuid>3ff9089e-4279-470d-9549-1b9e4c9906e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>a185066f-fd88-4c2b-ae47-12f7afba5ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>188</value>
      <webElementGuid>463acc5d-d2b7-46a7-8176-4f69b526e7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==</value>
      <webElementGuid>fcd6da24-c9ec-4c9b-a13f-9649b6249122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>aed981d8-8c83-414a-82ff-4742eac4a4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>05edae68-8ace-4a91-949d-1aadc0130a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=240&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 240w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=480&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 480w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=768&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 768w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=1024&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1024w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=1280&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1280w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=1440&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1440w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=1680&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 1680w,https://dm.henkel-dam.com/is/image/henkel/SKP_SHB_eAcademy-IGORA-Royal-Model?wid=2560&amp;fmt=webp&amp;qlt=90&amp;fit=hfit,1 2560w</value>
      <webElementGuid>af6e0dea-3689-43b1-80d5-7dc4566106c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratiobackground-885f840f84&quot;)/picture[@class=&quot;image__imgPreview image__imgPreview--lazy&quot;]/img[@class=&quot;image__img&quot;]</value>
      <webElementGuid>eb5e9696-6ea5-4e79-a911-88095cd90d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ratiobackground-885f840f84']/picture/img</value>
      <webElementGuid>0f6d5671-60c3-4ea7-b4d2-735c960ddfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Model with scarab coloured hair'])[3]</value>
      <webElementGuid>482778d7-85ec-4e96-953d-325c89e5cf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-stage[3]/div/div[2]/div/div/picture/img</value>
      <webElementGuid>a7d770b8-81ef-43e1-99ac-2306c3332d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Model with scarab coloured hair' and @src = 'data:image/gif;base64,R0lGODlhAQABAKECAAAAAP///yAhJSAhJSH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==']</value>
      <webElementGuid>d99e91b8-dffe-4950-a88d-ebc8379c17df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
