<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loctite</name>
   <tag></tag>
   <elementGuidId>a8ded924-f01f-4477-8ab7-e2b238efe41d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navigation-4f5705c219']/ul/li[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09e6080e-26b8-4483-8d3f-d6f50ace9a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>fa2d043d-3c03-4a33-a183-2ea89b0609a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/loctite.html</value>
      <webElementGuid>cd3f2f19-ff42-4866-b094-adccf4cb4c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Loctite</value>
      <webElementGuid>62acefec-ff3d-4678-9685-f640f39bee7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f5ffe14-fb9f-4ef4-a294-aae6c86df928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigation__item-link navigation__item-link--level-0</value>
      <webElementGuid>f27a3878-7e47-4845-9ada-6068b02fbc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a44e0f6c-ad39-44e6-b02c-67c00d8d21de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
       
            Loctite
        
    </value>
      <webElementGuid>bfe91e21-effc-474b-b0da-d46e3068f7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-4f5705c219&quot;)/ul[@class=&quot;navigation__group navigation__group--level-0&quot;]/li[@class=&quot;navigation__item navigation__item--level-0&quot;]/div[@class=&quot;navigation__item-content&quot;]/a[@class=&quot;navigation__item-link navigation__item-link--level-0&quot;]</value>
      <webElementGuid>bbec9634-1db7-42fe-ab37-581027a78ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation-4f5705c219']/ul/li[2]/div/a</value>
      <webElementGuid>9c5b2492-e0d5-40f5-95b0-dc2d84332e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge'])[1]/following::a[1]</value>
      <webElementGuid>5de6fc93-aa70-4e29-a4bb-2841400cfe9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile navigation'])[1]/following::a[2]</value>
      <webElementGuid>14bbc5cb-c86e-45cd-becf-423683fecbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::a[1]</value>
      <webElementGuid>659bbd58-5129-43f3-9908-776e7d50639a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/loctite.html')]</value>
      <webElementGuid>137f5db1-6014-4a26-a996-df51dbd6862f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>7d60aaa3-c868-47d3-b029-537b373a2b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www-beta-henkel-adhesives-com.ref.web.raqn.io/us/en/loctite.html' and @title = 'Loctite' and (text() = '
       
            Loctite
        
    ' or . = '
       
            Loctite
        
    ')]</value>
      <webElementGuid>22b3848e-47e6-4ce0-a24b-f371113ecaf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
