<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heliux-icon</name>
   <tag></tag>
   <elementGuidId>27ad1c64-091c-4c08-9a69-1a3de47c09fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login__button.login__button--login.cta > heliux-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>heliux-icon</value>
      <webElementGuid>fcaeb594-f743-4b97-920d-14bc2c953298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login--loggedOut login1672834451901&quot;]/button[@class=&quot;login__button login__button--login cta&quot;]/heliux-icon[1]</value>
      <webElementGuid>c8bfc17a-5aaf-43ba-807c-c32fd0b31d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      <webElementGuid>839e7705-2c74-4171-88fb-fde2d99bcf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear search history'])[1]/following::heliux-icon[3]</value>
      <webElementGuid>9f579637-3439-4748-a28e-e1b531748207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/following::heliux-icon[6]</value>
      <webElementGuid>0c7605f5-92c4-42f6-b78b-7f498fc68196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>5f2aef86-bdff-4e0e-aaad-c630dafa88b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>3e31f89c-f6d9-4f1d-ad71-4ff533d1ab58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-login/div/button/heliux-icon</value>
      <webElementGuid>8f30570a-53e8-4418-a75e-920938288e77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
