<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heliux-icon</name>
   <tag></tag>
   <elementGuidId>27ad1c64-091c-4c08-9a69-1a3de47c09fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.login__button.login__button--login.cta > heliux-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>heliux-icon</value>
      <webElementGuid>e1adaef6-5854-4896-9f1d-987a8156ad31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login--loggedOut login1672834451901&quot;]/button[@class=&quot;login__button login__button--login cta&quot;]/heliux-icon[1]</value>
      <webElementGuid>760722a8-0686-4115-98d3-09d25ef467db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      <webElementGuid>67e76bf9-2582-4a6b-afd3-022d77c4e763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear search history'])[1]/following::heliux-icon[3]</value>
      <webElementGuid>0bb3efc7-b914-4876-9069-166005d42e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/following::heliux-icon[6]</value>
      <webElementGuid>586bbf66-d1a9-4776-9ef7-cf74003ec174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>83340eb8-d7a1-454e-8d47-d7c8ef18d7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>e8f1c983-d61e-43ce-9612-c36c3c4cd400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-login/div/button/heliux-icon</value>
      <webElementGuid>e7b42030-d633-4cc3-87b7-866ddf022c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
