<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heliux-icon</name>
   <tag></tag>
   <elementGuidId>27ad1c64-091c-4c08-9a69-1a3de47c09fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.login__button.login__button--login.cta > heliux-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>heliux-icon</value>
      <webElementGuid>9eee9c1d-69cb-4e22-b852-399588d855ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-controls&quot;)/heliux-login[@class=&quot;login&quot;]/div[@class=&quot;login__wrapper login--loggedOut login1672834451901&quot;]/button[@class=&quot;login__button login__button--login cta&quot;]/heliux-icon[1]</value>
      <webElementGuid>b1637b41-a65e-4fa9-9f72-7727d81f72b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-controls']/heliux-login/div/button/heliux-icon</value>
      <webElementGuid>2628a87e-306f-4dfc-b9b4-8e7428fec98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear search history'])[1]/following::heliux-icon[3]</value>
      <webElementGuid>8a783743-d0e0-4e18-838a-7976982651e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/following::heliux-icon[6]</value>
      <webElementGuid>ebc42a18-d5dc-4a36-8a31-4d2e70ded99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>fd6242ea-07ad-48dc-97ec-b1f6de1344df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::heliux-icon[3]</value>
      <webElementGuid>d5a4fb14-ac40-4f5f-8e5c-98d4ebe5b7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//heliux-login/div/button/heliux-icon</value>
      <webElementGuid>503e6ac3-23f1-49e0-bd96-71661c815d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
