<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirmer la slection_btn__calltoact_eb17b8</name>
   <tag></tag>
   <elementGuidId>488dfe4a-513f-4d78-b7ac-c64e8b8513ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn__calltoaction-6c91904083</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn__calltoaction-6c91904083']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13bc59ac-022f-459a-a6d9-9bc16a710cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calltoaction__link cta  </value>
      <webElementGuid>3e428bd1-78ed-4005-a80d-c0af56290c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn__calltoaction-6c91904083</value>
      <webElementGuid>33152daa-7fd2-4be0-bda0-39aa88054e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-customizationclass</name>
      <type>Main</type>
      <value>customizations__calltoaction</value>
      <webElementGuid>18f5a658-5718-4989-a3b2-024845555b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close button</value>
      <webElementGuid>003a419f-35b4-4599-8a2b-3f098d7a24da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aria-label-initial</name>
      <type>Main</type>
      <value>Close button</value>
      <webElementGuid>4533f997-4d1a-4959-9db2-2fb7c3116691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components-params-calltoactionmodalcontrol</name>
      <type>Main</type>
      <value>{&quot;active&quot;:false,&quot;visible&quot;:true,&quot;addToCart&quot;:false,&quot;action&quot;:&quot;close&quot;}</value>
      <webElementGuid>ca837bba-f0cd-44c0-943f-f2e7ae562fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-components</name>
      <type>Main</type>
      <value>CallToActionModalControl</value>
      <webElementGuid>c9920b57-d3ae-4be8-8080-cdb9617d174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn__calltoaction-6c91904083&quot;)</value>
      <webElementGuid>1c6c7583-4382-4c94-b162-c3e5207dbbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn__calltoaction-6c91904083']</value>
      <webElementGuid>41951848-645b-459d-8793-c46a654ae318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-calltoaction-6c91904083']/div/button</value>
      <webElementGuid>a02230ed-1fcf-4741-ac31-f6940f7d8b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmer la sélection'])[1]/following::button[1]</value>
      <webElementGuid>a103d40c-468b-4641-a7f8-5dfe5f1b7212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout refuser'])[1]/following::button[2]</value>
      <webElementGuid>ff988d9f-f8c3-43fe-9d51-c3fa9b0f590c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recevez les nouveautés, actus et offres Schwarzkopf Professional !'])[1]/preceding::button[1]</value>
      <webElementGuid>d1745f08-823a-4271-9404-143697aac0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout savoir sur l’utilisation de vos données et de vos droits.'])[1]/preceding::button[1]</value>
      <webElementGuid>00c29fdb-f449-4bd9-9e07-fecd03433a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/heliux-section/div[3]/heliux-calltoaction/div[2]/div/button</value>
      <webElementGuid>95cabe6c-635f-4a78-8a4b-adb8cc62d10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn__calltoaction-6c91904083']</value>
      <webElementGuid>a84c5a3a-456b-45e8-a19b-aeeb7af820ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
