<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Merci pour votre inscription  notre news_44bed9</name>
   <tag></tag>
   <elementGuidId>6c9a344c-516b-4233-a940-5cd1d051d67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-profile-form > div.gigya-layout-row > h2.gigya-composite-control.gigya-composite-control-header.thank-you-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-profile-form']/div[12]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f43b2d9c-5bf9-4e4b-8e24-294bbe85629b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-composite-control gigya-composite-control-header thank-you-page</value>
      <webElementGuid>69e51d4f-06de-4763-95d7-ec970456534f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2ff12bd-3f53-4373-a97c-5376420f5a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>HEADER_158434311060357540_LABEL</value>
      <webElementGuid>3b22f14b-27ef-47c5-bb77-73e8690df066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_277_1676540714918</value>
      <webElementGuid>ba71f689-8717-465c-a045-7a282d3d3b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad599955-24dd-4fc3-8f7f-a8ab04bfd9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>template,instance,instance</value>
      <webElementGuid>4303c133-8c98-4b5c-841f-feff8185e5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merci pour votre inscription à notre newsletter ! À très vite :)</value>
      <webElementGuid>dd1f6c67-9827-4a87-b219-f684bf9b32a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-profile-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/h2[@class=&quot;gigya-composite-control gigya-composite-control-header thank-you-page&quot;]</value>
      <webElementGuid>a47b8553-db08-421e-8f4e-1385afca5329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-profile-form']/div[12]/h2</value>
      <webElementGuid>2f19d7f9-ed24-4364-862b-984a461b94e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tout savoir sur l’utilisation de vos données et de vos droits.'])[1]/following::h2[1]</value>
      <webElementGuid>643776cb-03e5-4c63-9865-b9ea8c87707e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recevez les nouveautés, actus et offres Schwarzkopf Professional !'])[1]/following::h2[1]</value>
      <webElementGuid>c218357f-48dd-4a31-884d-8760ec9de0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Merci pour votre inscription à notre newsletter ! À très vite :)']/parent::*</value>
      <webElementGuid>cbbae513-d41b-4eca-b46b-37df364b1cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[12]/h2</value>
      <webElementGuid>561a0949-982c-435f-9a9c-aafbac34e725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Merci pour votre inscription à notre newsletter ! À très vite :)' or . = 'Merci pour votre inscription à notre newsletter ! À très vite :)')]</value>
      <webElementGuid>21fe78a0-97f8-4631-a26d-64fd3b6fbffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
