<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tout savoir sur lutilisation de vos d_eb78b4</name>
   <tag></tag>
   <elementGuidId>d8681086-a6d9-404c-8f13-06cd0d59cafe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-profile-form > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-submit.button_newsletter > input.gigya-input-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value=&quot;JE M'INSCRIS&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ea29b2b-abbe-45aa-84ea-ac638b2754d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e517b71e-07bb-457d-9ae3-79595fe0e447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-submit</value>
      <webElementGuid>3ff3f8da-71d7-4587-add5-1658ad6ff763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>469b37be-6c4e-4ab4-9406-9504426670a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:value</name>
      <type>Main</type>
      <value>screenset.translations['SUBMIT_58960758316954150_VALUE']</value>
      <webElementGuid>193fd027-3712-4303-89c0-39cfbc272f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_278_1676540714919</value>
      <webElementGuid>08fd7d2b-64a6-4a96-9c42-220001594cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6da67a59-8773-4bb5-9fb7-653e07c19c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>6163d0ea-501e-4f32-a7ad-39826d801af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>JE M'INSCRIS</value>
      <webElementGuid>ede55a72-a2fc-40eb-b076-efc2e80fda39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-profile-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-submit button_newsletter&quot;]/input[@class=&quot;gigya-input-submit&quot;]</value>
      <webElementGuid>b34ab52a-fc66-4fd4-aaa0-9cda8cf44074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value=&quot;JE M'INSCRIS&quot;]</value>
      <webElementGuid>e6fe9219-af17-4c65-aa8c-e24a56edc0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-profile-form']/div[6]/div/input</value>
      <webElementGuid>c8365d81-60e0-41f1-9066-5d6ed2e979f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[6]/div/input</value>
      <webElementGuid>7107f1b3-bdb7-4c24-be57-288a03e33acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>746d756f-6291-48d7-9702-7abfcc2d384b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
